//! Fixed campaign execution inside one owned LINE or LANDING system VM.
//!
//! The controller supplies the already verified boot identity and frozen images.
//! This helper owns every child; it never reads PID files or signals unrelated
//! processes. Private inputs and retained evidence use separate directories.

use super::{collect, schema};
use crate::{
    bench::{
        origin_go::{self, OriginPlan},
        process::Child,
        slot,
    },
    process::Tool,
};
use clap::{Args, ValueEnum};
use std::{
    fs,
    io::Write as _,
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

pub const ROOT: &str = "/home/rrtest/rr-stability";

/// The only guest roles in the maintained fixture.
#[derive(Clone, Copy, Debug, PartialEq, Eq, ValueEnum)]
pub enum Role {
    /// Shared destination of both LINE nodes.
    Landing,
    /// First independent ingress.
    LineA,
    /// Second independent ingress.
    LineB,
}

impl Role {
    /// Stable evidence role name.
    pub const fn name(self) -> &'static str {
        match self {
            Self::Landing => "landing",
            Self::LineA => "line-a",
            Self::LineB => "line-b",
        }
    }
}

/// Internal guest invocation, generated by the owned-fixture controller.
#[derive(Args)]
pub struct Plan {
    /// Fixed role in the three-guest topology.
    #[arg(long, value_enum)]
    pub role: Role,
    /// Absolute workload epoch fixed before any helper starts.
    #[arg(long)]
    pub started_unix_ms: u64,
    /// Boot identity observed by the controller after owning QEMU.
    #[arg(long)]
    pub boot_id: String,
    /// Frozen product executable digest.
    #[arg(long)]
    pub candidate_sha256: String,
    /// Frozen helper/evaluator executable digest.
    #[arg(long)]
    pub evaluator_sha256: String,
    /// Frozen stock-Xray executable digest.
    #[arg(long)]
    pub xray_sha256: String,
}

#[derive(Debug, PartialEq, Eq)]
enum Event {
    Capture(String),
    Begin(String),
    End(String),
}

fn schedule(contract: &schema::Contract) -> Vec<(u64, Event)> {
    let mut events = Vec::new();
    for index in 0..contract.cycles {
        let start = u64::try_from(index).expect("bounded contract") * contract.cycle_interval_ms;
        for offset in &contract.checkpoint_offsets_ms {
            events.push((
                start + offset,
                Event::Capture(format!("cycle-{index}-{offset}")),
            ));
        }
    }
    let faults_start =
        u64::try_from(contract.cycles).expect("bounded contract") * contract.cycle_interval_ms;
    for (index, name) in contract.faults.iter().enumerate() {
        let start = faults_start
            + u64::try_from(index).expect("bounded contract") * contract.fault_interval_ms;
        events.push((start, Event::Begin(name.clone())));
        events.push((
            start + contract.fault_duration(name),
            Event::End(name.clone()),
        ));
        for offset in &contract.fault_checkpoint_offsets_ms {
            events.push((
                start + offset,
                Event::Capture(format!("fault-{name}-{offset}")),
            ));
        }
    }
    for offset in contract.integrity_offsets() {
        events.push((
            contract.integrity_start() + offset,
            Event::Capture(format!("integrity-{offset}")),
        ));
    }
    events.sort_by_key(|(offset, _)| *offset);
    events
}

fn save(path: &Path, value: &impl serde::Serialize) -> Result<(), String> {
    let bytes = serde_json::to_vec(value).map_err(|error| error.to_string())?;
    fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .and_then(|mut file| file.write_all(&bytes))
        .map_err(|error| format!("write fresh guest evidence: {error}"))?;
    // Forward every completed receipt immediately. A later SSH/SFTP failure
    // must not erase observations already collected inside a temporary VM.
    let mut output = std::io::stdout().lock();
    output
        .write_all(b"{\"name\":")
        .map_err(|error| error.to_string())?;
    serde_json::to_writer(
        &mut output,
        &path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or("invalid evidence filename")?,
    )
    .map_err(|error| error.to_string())?;
    output
        .write_all(b",\"value\":")
        .and_then(|()| output.write_all(&bytes))
        .and_then(|()| output.write_all(b"}\n"))
        .and_then(|()| output.flush())
        .map_err(|error| format!("stream guest evidence: {error}"))
}

struct Session<'a> {
    plan: &'a Plan,
    root: PathBuf,
    output: PathBuf,
    server: Option<Child>,
    helpers: Vec<(Child, String)>,
    clock: (u64, Instant),
}

impl Session<'_> {
    fn start_child(
        &self,
        label: &str,
        receipt: &str,
        program: &Path,
        args: &[String],
        port: u16,
    ) -> Result<Child, String> {
        let mut child = Child::spawn_isolated(
            label,
            program,
            args,
            &self.root,
            &[
                (
                    "PATH".to_owned(),
                    "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin".to_owned(),
                ),
                (
                    "SSL_CERT_FILE".to_owned(),
                    self.root.join("ca.crt").display().to_string(),
                ),
            ],
            &self.output.join(format!("{label}.log")),
        )
        .map_err(|error| error.to_string())?;
        let ready = child.wait_for_port(port, Duration::from_secs(10));
        let identity = collect::file_digest(Path::new(&format!("/proc/{}/exe", child.pid())));
        let written = save(
            &self.output.join(format!("startup-{receipt}.json")),
            &serde_json::json!({
                "label":label,"pid":child.pid(),"start_ticks":crate::bench::process::proc_starttime(child.pid()),
                "image_sha256":identity.as_ref().ok(),"image_error":identity.as_ref().err(),
                "readiness_error":ready.as_ref().err().map(ToString::to_string),
            }),
        );
        if let Err(error) = ready {
            return Err(match written {
                Ok(()) => error.to_string(),
                Err(secondary) => format!("{error}; startup finalization also failed: {secondary}"),
            });
        }
        written?;
        Ok(child)
    }

    fn start_server(&mut self, restart: bool) -> Result<(), String> {
        let candidate = self.root.join("rust-reality");
        if collect::file_digest(&candidate)? != self.plan.candidate_sha256 {
            return Err("guest product image changed".to_owned());
        }
        let child = self.start_child(
            "server",
            if restart {
                "server-after-restart"
            } else {
                "server"
            },
            Path::new("/usr/bin/prlimit"),
            &[
                "--nofile=8192:8192".to_owned(),
                candidate.display().to_string(),
                "serve".to_owned(),
                "--config".to_owned(),
                self.root.join("server.json").display().to_string(),
            ],
            if self.plan.role == Role::Landing {
                9443
            } else {
                9444
            },
        )?;
        slot::verify_running_image(child.pid(), &self.plan.candidate_sha256, "guest candidate")?;
        self.server = Some(child);
        Ok(())
    }

    fn initialize(&mut self) -> Result<(), String> {
        let harness = self.root.join("rr-dev");
        if collect::file_digest(&std::env::current_exe().map_err(|error| error.to_string())?)?
            != self.plan.evaluator_sha256
            || collect::file_digest(&harness)? != self.plan.evaluator_sha256
        {
            return Err("guest harness image differs from the frozen evaluator".to_owned());
        }
        if self.plan.role == Role::Landing {
            for (label, port, tls) in [("http-origin", 8080, false), ("tls-origin", 8443, true)] {
                let args = origin_go::listener_args(&OriginPlan {
                    label: label.to_owned(),
                    listen_address: "0.0.0.0".to_owned(),
                    port,
                    payload_dir: self.root.clone(),
                    put_log: self.output.join(format!("{label}-put.jsonl")),
                    tls: tls.then(|| (self.root.join("server.crt"), self.root.join("server.key"))),
                    access_log: Some(self.output.join(format!("{label}-access.jsonl"))),
                    alpn: None,
                });
                let child = self.start_child(label, label, &harness, &args, port)?;
                self.helpers
                    .push((child, self.plan.evaluator_sha256.clone()));
            }
            let child = self.start_child(
                "echo",
                "echo",
                &harness,
                &[
                    "bench".to_owned(),
                    "echo".to_owned(),
                    "--port".to_owned(),
                    "8081".to_owned(),
                ],
                8081,
            )?;
            self.helpers
                .push((child, self.plan.evaluator_sha256.clone()));
        }
        self.start_server(false)?;
        if self.plan.role != Role::Landing {
            let xray = self.root.join("xray");
            if collect::file_digest(&xray)? != self.plan.xray_sha256 {
                return Err("guest Xray image changed".to_owned());
            }
            let child = self.start_child(
                "xray",
                "xray",
                &xray,
                &[
                    "run".to_owned(),
                    "-config".to_owned(),
                    self.root.join("xray.json").display().to_string(),
                ],
                1080,
            )?;
            self.helpers.push((child, self.plan.xray_sha256.clone()));
        }
        if collect::unix_ms()?.saturating_add(3000) > self.plan.started_unix_ms {
            return Err(
                "guest initialization missed the fixed pre-workload settle deadline".to_owned(),
            );
        }
        Ok(())
    }

    fn alive(&mut self) -> Result<(), String> {
        for (child, _) in &mut self.helpers {
            if !child.is_alive() {
                return Err(format!("{} exited unexpectedly", child.label()));
            }
        }
        if let Some(server) = &mut self.server
            && !server.is_alive()
        {
            return Err("guest server exited unexpectedly".to_owned());
        }
        Ok(())
    }

    fn wait_until(&mut self, epoch: u64) -> Result<(), String> {
        loop {
            if self.root.join("stop").exists() {
                return Err(
                    "controller stopped the workload; final observations attempted".to_owned(),
                );
            }
            self.alive()?;
            let now = collect::unix_ms()?;
            let elapsed = u64::try_from(self.clock.1.elapsed().as_millis())
                .map_err(|_| "guest clock overflow")?;
            if now.abs_diff(self.clock.0.saturating_add(elapsed)) > 2000 {
                return Err("guest wall clock moved relative to monotonic execution".to_owned());
            }
            if now >= epoch {
                return Ok(());
            }
            std::thread::sleep(Duration::from_millis((epoch - now).min(100)));
        }
    }

    fn capture(&self, name: &str) -> Result<(), String> {
        let server = self
            .server
            .as_ref()
            .ok_or("no owned server for checkpoint")?;
        let raw = collect::observe(server.pid(), &self.output.join("server.log"))?;
        save(&self.output.join(format!("{name}.json")), &raw)?;
        if raw.errors.is_empty() && raw.closed_during_read.is_empty() {
            Ok(())
        } else {
            Err(format!("{name}: incomplete raw observation (retained)"))
        }
    }

    fn command(args: &[String], outcomes: &mut Vec<serde_json::Value>) -> Result<(), String> {
        let started = collect::unix_ms()?;
        let result = Tool::new("sudo")
            .arg("-n")
            .args(args)
            .timeout(Duration::from_secs(2))
            .probe();
        let completed = collect::unix_ms()?;
        outcomes.push(match &result {
            Ok(result) => serde_json::json!({"argv":args,"started_unix_ms":started,"completed_unix_ms":completed,"exit_code":result.code,"stdout":result.stdout,"stderr":result.stderr}),
            Err(error) => serde_json::json!({"argv":args,"started_unix_ms":started,"completed_unix_ms":completed,"error":error.to_string()}),
        });
        let result = result.map_err(|error| error.to_string())?;
        if result.success() {
            Ok(())
        } else {
            Err("guest fault command failed; receipt retained".to_owned())
        }
    }

    fn netem(
        &self,
        name: &str,
        begin: bool,
        outcomes: &mut Vec<serde_json::Value>,
    ) -> Result<(), String> {
        let interfaces: &[&str] = match (self.plan.role, name) {
            (Role::LineB, "line-a-partition") => &[],
            (Role::Landing, "line-a-partition") => &["data0"],
            (Role::Landing, _) => &["data0", "data1"],
            _ => &["data0"],
        };
        for interface in interfaces {
            let show: Vec<String> = ["tc", "-j", "qdisc", "show", "dev", interface]
                .into_iter()
                .map(str::to_owned)
                .collect();
            Self::command(&show, outcomes)?;
            let mut args: Vec<String> = [
                "tc",
                "qdisc",
                if begin { "replace" } else { "del" },
                "dev",
                interface,
                "root",
            ]
            .into_iter()
            .map(str::to_owned)
            .collect();
            if begin {
                args.push("netem".to_owned());
                if name == "line-a-partition" {
                    args.extend(["loss".to_owned(), "100%".to_owned()]);
                } else {
                    let delay = match name {
                        "rtt-50" => "25ms",
                        "rtt-100" | "rtt-100-loss-1" => "50ms",
                        "rtt-200" => "100ms",
                        _ => return Err("unknown RTT fault".to_owned()),
                    };
                    args.extend(["delay".to_owned(), delay.to_owned()]);
                    if name == "rtt-100-loss-1" {
                        args.extend(["loss".to_owned(), "1%".to_owned()]);
                    }
                }
            }
            Self::command(&args, outcomes)?;
            Self::command(&show, outcomes)?;
        }
        Ok(())
    }

    fn fault(&mut self, name: &str, begin: bool) -> Result<(), String> {
        let started = collect::unix_ms()?;
        let mut outcomes = Vec::new();
        let action = (|| match name {
            "reload" if begin => self
                .server
                .as_mut()
                .ok_or("missing reload server")?
                .reload(),
            "warm" | "cold" if self.plan.role != Role::Landing => {
                let variant = if name == "cold" && begin {
                    "cold.json"
                } else {
                    "warm.json"
                };
                fs::copy(self.root.join(variant), self.root.join("server-next.json"))
                    .map_err(|error| error.to_string())?;
                fs::rename(
                    self.root.join("server-next.json"),
                    self.root.join("server.json"),
                )
                .map_err(|error| error.to_string())?;
                self.server
                    .as_mut()
                    .ok_or("missing transition server")?
                    .reload()
            }
            "stale" if begin && self.plan.role == Role::Landing => Self::command(
                &[
                    "ss",
                    "-K",
                    "state",
                    "established",
                    "dst",
                    "192.0.2.5",
                    "(",
                    "sport",
                    "=",
                    ":9443",
                    ")",
                ]
                .map(str::to_owned),
                &mut outcomes,
            ),
            "landing-restart" if self.plan.role == Role::Landing => {
                if begin {
                    self.server
                        .as_mut()
                        .ok_or("missing restart server")?
                        .abort()?;
                    self.server.take();
                    fs::rename(
                        self.output.join("server.log"),
                        self.output.join("server-before-restart.log"),
                    )
                    .map_err(|error| error.to_string())?;
                    Ok(())
                } else {
                    self.start_server(true)
                }
            }
            "line-a-partition" | "rtt-50" | "rtt-100" | "rtt-200" | "rtt-100-loss-1" => {
                self.netem(name, begin, &mut outcomes)
            }
            "reload" | "warm" | "cold" | "stale" | "landing-restart" => Ok(()),
            _ => Err("unknown fixed campaign fault".to_owned()),
        })();
        let written = save(
            &self.output.join(format!(
                "action-{name}-{}.json",
                if begin { "begin" } else { "end" }
            )),
            &serde_json::json!({
                "role":self.plan.role.name(),"boot_id":self.plan.boot_id,"started_unix_ms":started,"completed_unix_ms":collect::unix_ms()?,
                "name":name,"begin":begin,"commands":outcomes,"error":action.as_ref().err(),
            }),
        );
        match (action, written) {
            (Err(primary), Err(secondary)) => Err(format!(
                "{primary}; action evidence also failed: {secondary}"
            )),
            (Err(error), _) | (_, Err(error)) => Err(error),
            _ => Ok(()),
        }
    }

    fn execute(&mut self) -> Result<(), String> {
        self.initialize()?;
        let contract: schema::Contract =
            serde_json::from_str(schema::CONTRACT).expect("compiled contract");
        for (offset, event) in schedule(&contract) {
            let epoch = self
                .plan
                .started_unix_ms
                .checked_add(offset)
                .ok_or("guest schedule overflow")?;
            self.wait_until(epoch)?;
            match event {
                Event::Capture(name) => self.capture(&name)?,
                Event::Begin(name) => self.fault(&name, true)?,
                Event::End(name) => self.fault(&name, false)?,
            }
            if collect::unix_ms()?.saturating_sub(epoch) > contract.checkpoint_tolerance_ms {
                return Err(format!("guest event at {offset} missed its fixed deadline"));
            }
        }
        Ok(())
    }
}

/// Run the fixed schedule in the verified guest and always attempt final evidence.
///
/// # Errors
/// Returns the original execution failure followed by any finalization failures.
pub fn run(plan: &Plan) -> Result<(), String> {
    let boot =
        fs::read_to_string("/proc/sys/kernel/random/boot_id").map_err(|error| error.to_string())?;
    if boot.trim() != plan.boot_id || plan.boot_id.is_empty() {
        return Err("guest boot identity mismatch".to_owned());
    }
    run_in(plan, PathBuf::from(ROOT))
}

fn run_in(plan: &Plan, root: PathBuf) -> Result<(), String> {
    let output = root.join("output");
    fs::create_dir(&output).map_err(|error| format!("fresh guest evidence directory: {error}"))?;
    let mut session = Session {
        plan,
        root,
        output,
        server: None,
        helpers: Vec::new(),
        clock: (collect::unix_ms()?, Instant::now()),
    };
    let primary = session.execute();
    let mut finalization = Vec::new();
    if let Err(error) = session.capture("terminal") {
        finalization.push(error);
    }
    if let Some(server) = &session.server
        && let Err(error) =
            slot::verify_running_image(server.pid(), &plan.candidate_sha256, "guest server")
    {
        finalization.push(error);
    }
    for (child, expected) in &session.helpers {
        if let Err(error) = slot::verify_running_image(child.pid(), expected, child.label()) {
            finalization.push(error);
        }
    }
    if let Err(error) = save(
        &session.output.join("terminal-status.json"),
        &serde_json::json!({
            "role":plan.role.name(),"boot_id":plan.boot_id,"started_unix_ms":plan.started_unix_ms,
            "candidate_sha256":plan.candidate_sha256,"evaluator_sha256":plan.evaluator_sha256,
            "primary_error":primary.as_ref().err(),"finalization_errors":finalization,
        }),
    ) {
        finalization.push(error);
    }
    if let Err(error) = primary {
        finalization.insert(0, error);
    }
    if finalization.is_empty() {
        Ok(())
    } else {
        Err(finalization.join("; "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn a_guest_receipt_is_never_replaced_by_a_later_attempt() {
        let workspace =
            crate::bench::workspace::Workspace::create("guest-immutable-receipt").unwrap();
        let path = workspace.join("receipt.json");
        save(&path, &serde_json::json!({"attempt":1})).unwrap();
        let original = fs::read(&path).unwrap();
        assert!(save(&path, &serde_json::json!({"attempt":2})).is_err());
        assert_eq!(fs::read(path).unwrap(), original);
    }
    #[test]
    fn guest_start_failure_retains_primary_and_attempted_final_observation() {
        let workspace = crate::bench::workspace::Workspace::create("guest-finalization").unwrap();
        let plan = Plan {
            role: Role::LineA,
            started_unix_ms: 0,
            boot_id: "test-boot".to_owned(),
            candidate_sha256: "a".repeat(64),
            evaluator_sha256: "b".repeat(64),
            xray_sha256: "c".repeat(64),
        };
        let result = run_in(&plan, workspace.path().to_path_buf());
        assert!(result.is_err());
        let receipt: serde_json::Value = serde_json::from_slice(
            &fs::read(workspace.join("output/terminal-status.json")).unwrap(),
        )
        .unwrap();
        assert!(receipt["primary_error"].is_string());
        assert_eq!(
            receipt["finalization_errors"][0],
            "no owned server for checkpoint"
        );
    }
    #[test]
    fn guest_schedule_covers_every_fixed_cycle_and_fault_checkpoint() {
        let contract: schema::Contract = serde_json::from_str(schema::CONTRACT).unwrap();
        let events = schedule(&contract);
        assert_eq!(
            events.len(),
            contract.cycles * contract.checkpoint_offsets_ms.len()
                + contract.faults.len() * (contract.fault_checkpoint_offsets_ms.len() + 2)
                + 4
        );
        assert_eq!(
            events.first(),
            Some(&(0, Event::Capture("cycle-0-0".to_owned())))
        );
        assert!(events.windows(2).all(|pair| pair[0].0 <= pair[1].0));
    }
}
