//! Native hotspot bundle export and instruction aggregation.
//!
//! Rust owns the input path, capture identity, `IDALib` isolation, output schema,
//! sample mapping gates, checksums, failure state and publication. `IDALib` exposes
//! its automation API through Python, so the only Python retained here is a
//! generated private bridge containing direct IDA API calls. It has no argument,
//! path, identity, verdict or publication policy of its own.

#![allow(
    clippy::cast_precision_loss,
    clippy::too_many_lines,
    reason = "the bounded export lifecycle and evidence schemas are intentionally explicit"
)]

use std::{
    cmp::Ordering,
    fmt::Write as _,
    fs::OpenOptions,
    io::Write as _,
    os::unix::fs::{DirBuilderExt as _, PermissionsExt as _},
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use crate::{
    bench::{attest, evidence::RunDirectory, publication},
    hash,
    perf::{json_in, json_out::Json},
    process::Tool,
};

const MAX_TIMEOUT_SECONDS: u64 = 1_800;
const MAX_PERF_DATA_BYTES: u64 = 1024 * 1024 * 1024;
const MAX_FUNCTION_BYTES: u64 = 64 * 1024 * 1024;
const MAX_INSTRUCTIONS: usize = 4_000_000;
const HARD_UNMAPPED_PERCENT: f64 = 1.0;

const IDALIB_BRIDGE: &str = r#"# Generated by rr-dev. IDALib requires this import to be first.
import idapro
import json
import sys
import traceback

import ida_auto
import ida_bytes
import ida_funcs
import ida_hexrays
import ida_lines
import ida_name
import ida_ua


def main():
    input_path, address_text, output_path = sys.argv[1:]
    requested = int(address_text, 0)
    result = idapro.open_database(input_path, True)
    if result != 0:
        raise RuntimeError(f"idapro.open_database failed with code {result}")
    try:
        if not ida_auto.auto_wait():
            raise RuntimeError("IDA auto-analysis was cancelled")
        function = ida_funcs.get_func(requested)
        if function is None:
            raise RuntimeError(f"no IDA function contains 0x{requested:x}")
        start = function.start_ea
        end = function.end_ea
        instructions = []
        address = start
        while address < end:
            instruction = ida_ua.insn_t()
            size = ida_ua.decode_insn(instruction, address)
            if size <= 0:
                address += 1
                continue
            raw = ida_bytes.get_bytes(address, size) or b""
            text = ida_lines.generate_disasm_line(
                address, ida_lines.GENDSM_REMOVE_TAGS
            )
            instructions.append({
                "address": f"0x{address:x}",
                "size": size,
                "bytes": raw.hex(),
                "text": text or "",
            })
            address += size
        if not ida_hexrays.init_hexrays_plugin():
            raise RuntimeError("Hex-Rays Decompiler is unavailable")
        cfunc = ida_hexrays.decompile(start)
        if cfunc is None:
            raise RuntimeError(f"Hex-Rays failed to decompile 0x{start:x}")
        pseudocode = "\n".join(
            ida_lines.tag_remove(line.line) for line in cfunc.get_pseudocode()
        )
        result = {
            "requestedAddress": f"0x{requested:x}",
            "function": {
                "name": ida_name.get_ea_name(start),
                "start": f"0x{start:x}",
                "end": f"0x{end:x}",
            },
            "instructions": instructions,
            "pseudocode": pseudocode,
        }
        with open(output_path, "x", encoding="utf-8") as output:
            json.dump(result, output, ensure_ascii=False, separators=(",", ":"))
            output.write("\n")
    finally:
        idapro.close_database()


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        raise SystemExit(1)
"#;

/// One export request rooted in a completed native hotspot capture.
#[derive(Debug, Clone)]
pub struct Plan {
    /// Completed `cargo dev perf hotspot` run directory.
    pub run_dir: PathBuf,
    /// Safe evidence label.
    pub label: String,
    /// Static ELF address inside the selected function.
    pub address: String,
    /// `IDALib` Python executable.
    pub idalib_python: PathBuf,
    /// `IDALib` timeout.
    pub timeout_seconds: u64,
    /// Reviewed soft threshold below the hard one-percent gate.
    pub max_unmapped_period_percent: f64,
    /// Explanation required for a non-zero threshold.
    pub unmapped_period_explanation: Option<String>,
}

#[derive(Debug)]
struct Capture {
    root: PathBuf,
    run_id: String,
    binary: PathBuf,
    binary_sha256: String,
    binary_build_id: String,
    perf_data: PathBuf,
}

#[derive(Debug, Clone)]
struct Instruction {
    address: u64,
    size: u64,
    bytes: String,
    text: String,
    sample_count: u64,
    period_sum: u64,
}

#[derive(Debug)]
struct Function {
    name: String,
    start: u64,
    end: u64,
    instructions: Vec<Instruction>,
    pseudocode: String,
}

#[derive(Debug)]
struct Sample {
    period: u64,
    offset: u64,
    source: String,
}

#[derive(Debug, Default)]
struct Totals {
    sample_rows: u64,
    period_sum: u64,
    mapped_rows: u64,
    mapped_period: u64,
    unmapped_rows: u64,
    unmapped_period: u64,
}

fn safe_component(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes
        .next()
        .is_some_and(|byte| byte.is_ascii_alphanumeric())
        && value.len() <= 96
        && bytes.all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

fn parse_address(value: &str, context: &str) -> Result<u64, String> {
    let digits = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
        .ok_or_else(|| format!("{context} must be hexadecimal with a 0x prefix"))?;
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(format!("{context} must be hexadecimal with a 0x prefix"));
    }
    u64::from_str_radix(digits, 16).map_err(|error| format!("invalid {context}: {error}"))
}

fn valid_lower_hex(value: &str, length: Option<usize>) -> bool {
    length.is_none_or(|expected| value.len() == expected)
        && !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn regular_not_symlink(path: &Path, context: &str) -> Result<(), String> {
    let metadata = path
        .symlink_metadata()
        .map_err(|error| format!("could not stat {context} {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(format!(
            "{context} is not a regular non-symlink file: {}",
            path.display()
        ));
    }
    Ok(())
}

/// Validates bounded arguments without invoking `IDALib` or perf.
///
/// # Errors
///
/// Returns one actionable argument diagnostic.
pub fn validate(plan: &Plan) -> Result<(), String> {
    if !plan.run_dir.is_absolute() {
        return Err("--run-dir must be absolute".to_owned());
    }
    if !safe_component(&plan.label) {
        return Err("--label must be a 1..=96 character safe identifier".to_owned());
    }
    parse_address(&plan.address, "--address")?;
    if !plan.idalib_python.is_absolute() {
        return Err("--idalib-python must be absolute".to_owned());
    }
    regular_not_symlink(&plan.idalib_python, "IDALib Python")?;
    let mode = plan
        .idalib_python
        .metadata()
        .map_err(|error| format!("could not stat IDALib Python: {error}"))?
        .permissions()
        .mode();
    if mode & 0o111 == 0 {
        return Err("--idalib-python must be executable".to_owned());
    }
    if plan.timeout_seconds == 0 || plan.timeout_seconds > MAX_TIMEOUT_SECONDS {
        return Err("--timeout-seconds must be in 1..=1800".to_owned());
    }
    if !plan.max_unmapped_period_percent.is_finite()
        || !(0.0..HARD_UNMAPPED_PERCENT).contains(&plan.max_unmapped_period_percent)
    {
        return Err("--max-unmapped-period-percent must be in [0, 1)".to_owned());
    }
    match (
        plan.max_unmapped_period_percent > 0.0,
        plan.unmapped_period_explanation
            .as_deref()
            .is_some_and(|value| !value.trim().is_empty()),
    ) {
        (true, false) => {
            return Err(
                "a non-zero mapping threshold requires --unmapped-period-explanation".to_owned(),
            );
        }
        (false, true) => {
            return Err("an unmapped-period explanation requires a non-zero threshold".to_owned());
        }
        _ => {}
    }
    Ok(())
}

fn read_json(path: &Path, context: &str) -> Result<json_in::Value, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|error| format!("could not read {context} {}: {error}", path.display()))?;
    json_in::parse(&text).map_err(|error| format!("invalid {context} {}: {error}", path.display()))
}

fn load_capture(plan: &Plan) -> Result<Capture, String> {
    let root_metadata = plan.run_dir.symlink_metadata().map_err(|error| {
        format!(
            "could not stat --run-dir {}: {error}",
            plan.run_dir.display()
        )
    })?;
    if root_metadata.file_type().is_symlink() || !root_metadata.is_dir() {
        return Err("--run-dir must be an existing non-symlink directory".to_owned());
    }
    let root = plan
        .run_dir
        .canonicalize()
        .map_err(|error| format!("could not canonicalize --run-dir: {error}"))?;
    let metadata_path = root.join("metadata.json");
    let completion_path = root.join("run-completion.json");
    let perf_data = root.join("perf.data");
    for (path, context) in [
        (&metadata_path, "hotspot metadata"),
        (&completion_path, "hotspot completion"),
        (&perf_data, "perf data"),
    ] {
        regular_not_symlink(path, context)?;
    }
    let metadata = read_json(&metadata_path, "hotspot metadata")?;
    metadata
        .require_str("metadata", "state", "COMPLETE")
        .map_err(|error| error.to_string())?;
    let run_id = metadata
        .str_field("metadata", "runId")
        .map_err(|error| error.to_string())?
        .to_owned();
    let binary_sha256 = metadata
        .str_field("metadata", "binarySha256")
        .map_err(|error| error.to_string())?
        .to_owned();
    let binary_build_id = metadata
        .str_field("metadata", "binaryBuildId")
        .map_err(|error| error.to_string())?
        .to_owned();
    if !valid_lower_hex(&binary_sha256, Some(64)) || !valid_lower_hex(&binary_build_id, None) {
        return Err("hotspot capture binary identity is malformed".to_owned());
    }
    let completion = read_json(&completion_path, "hotspot completion")?;
    let contract_path = root.join("run-contract.json");
    let contract_sha256 =
        crate::perf::loader::sha256_file(&contract_path).map_err(|error| error.to_string())?;
    crate::perf::loader::verify_success_marker(
        &completion,
        &contract_path,
        &contract_sha256,
        &run_id,
        "perf-hotspot",
        "hotspot completion",
    )
    .map_err(|error| error.to_string())?;

    let binary_dir = root.join("binary");
    let entries = std::fs::read_dir(&binary_dir)
        .map_err(|error| format!("could not read {}: {error}", binary_dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("could not enumerate {}: {error}", binary_dir.display()))?;
    if entries.len() != 1 {
        return Err(format!(
            "hotspot capture must contain exactly one archived binary, found {}",
            entries.len()
        ));
    }
    let binary = entries[0].path();
    regular_not_symlink(&binary, "archived binary")?;
    if hash::sha256_file(&binary)? != binary_sha256 {
        return Err("archived binary SHA-256 does not match completed capture".to_owned());
    }
    if attest::build_id(&binary)? != binary_build_id {
        return Err("archived binary Build ID does not match completed capture".to_owned());
    }
    let perf_bytes = perf_data
        .metadata()
        .map_err(|error| format!("could not stat perf data: {error}"))?
        .len();
    if perf_bytes == 0 || perf_bytes > MAX_PERF_DATA_BYTES {
        return Err("perf data must be non-empty and no larger than 1 GiB".to_owned());
    }
    Ok(Capture {
        root,
        run_id,
        binary,
        binary_sha256,
        binary_build_id,
        perf_data,
    })
}

fn write_new(path: &Path, contents: &[u8]) -> Result<(), String> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| format!("could not create {}: {error}", path.display()))?;
    file.write_all(contents)
        .map_err(|error| format!("could not write {}: {error}", path.display()))?;
    file.sync_all()
        .map_err(|error| format!("could not sync {}: {error}", path.display()))
}

fn run_stdout_file(
    program: &Path,
    args: &[String],
    stdout: &Path,
    stderr: &Path,
) -> Result<(), String> {
    let stdout_file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(stdout)
        .map_err(|error| format!("could not create {}: {error}", stdout.display()))?;
    let stderr_file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(stderr)
        .map_err(|error| format!("could not create {}: {error}", stderr.display()))?;
    let status = Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::from(stdout_file))
        .stderr(Stdio::from(stderr_file))
        .status()
        .map_err(|error| format!("could not run {}: {error}", program.display()))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "{} failed with {}; see {}",
            program.display(),
            status,
            stderr.display()
        ))
    }
}

fn json_u64(value: u64, context: &str) -> Result<Json, String> {
    i64::try_from(value)
        .map(Json::Int)
        .map_err(|_| format!("{context} exceeds the JSON integer range"))
}

fn parse_idalib_result(path: &Path, requested: u64) -> Result<Function, String> {
    let result = read_json(path, "IDALib bridge result")?;
    let observed_requested = parse_address(
        result
            .str_field("idalib", "requestedAddress")
            .map_err(|error| error.to_string())?,
        "IDALib requestedAddress",
    )?;
    if observed_requested != requested {
        return Err("IDALib returned a different requested address".to_owned());
    }
    let function = result
        .field("idalib", "function")
        .map_err(|error| error.to_string())?;
    let name = function
        .str_field("idalib.function", "name")
        .map_err(|error| error.to_string())?
        .to_owned();
    if name.is_empty() {
        return Err("IDALib returned an empty function name".to_owned());
    }
    let start = parse_address(
        function
            .str_field("idalib.function", "start")
            .map_err(|error| error.to_string())?,
        "IDALib function start",
    )?;
    let end = parse_address(
        function
            .str_field("idalib.function", "end")
            .map_err(|error| error.to_string())?,
        "IDALib function end",
    )?;
    if end <= start || requested < start || requested >= end || end - start > MAX_FUNCTION_BYTES {
        return Err("IDALib returned an invalid or oversized function range".to_owned());
    }
    let raw_instructions = result
        .array_field("idalib", "instructions")
        .map_err(|error| error.to_string())?;
    if raw_instructions.is_empty() || raw_instructions.len() > MAX_INSTRUCTIONS {
        return Err("IDALib returned an empty or oversized instruction list".to_owned());
    }
    let mut instructions = Vec::with_capacity(raw_instructions.len());
    for (index, raw) in raw_instructions.iter().enumerate() {
        let context = format!("idalib.instructions[{index}]");
        let address = parse_address(
            raw.str_field(&context, "address")
                .map_err(|error| error.to_string())?,
            &format!("{context}.address"),
        )?;
        let size = u64::try_from(
            raw.int_field(&context, "size")
                .map_err(|error| error.to_string())?,
        )
        .map_err(|_| format!("{context}.size must be positive"))?;
        let bytes = raw
            .str_field(&context, "bytes")
            .map_err(|error| error.to_string())?
            .to_owned();
        let text = raw
            .str_field(&context, "text")
            .map_err(|error| error.to_string())?
            .to_owned();
        let byte_length = usize::try_from(size)
            .ok()
            .and_then(|value| value.checked_mul(2));
        if size == 0
            || address < start
            || address >= end
            || address.checked_add(size).is_none_or(|last| last > end)
            || Some(bytes.len()) != byte_length
            || !bytes.bytes().all(|byte| byte.is_ascii_hexdigit())
        {
            return Err(format!("invalid IDALib instruction at index {index}"));
        }
        instructions.push(Instruction {
            address,
            size,
            bytes,
            text,
            sample_count: 0,
            period_sum: 0,
        });
    }
    instructions.sort_by_key(|instruction| instruction.address);
    for pair in instructions.windows(2) {
        if pair[0].address + pair[0].size > pair[1].address {
            return Err("IDALib instruction ranges overlap".to_owned());
        }
    }
    let pseudocode = result
        .str_field("idalib", "pseudocode")
        .map_err(|error| error.to_string())?
        .to_owned();
    if pseudocode.trim().is_empty() {
        return Err("IDALib returned empty pseudocode".to_owned());
    }
    Ok(Function {
        name,
        start,
        end,
        instructions,
        pseudocode,
    })
}

fn instruction_json(instruction: &Instruction, function_start: u64) -> Result<Json, String> {
    Ok(Json::object([
        (
            "address",
            Json::string(format!("0x{:x}", instruction.address)),
        ),
        (
            "offset",
            Json::string(format!("0x{:x}", instruction.address - function_start)),
        ),
        ("size", json_u64(instruction.size, "instruction size")?),
        ("bytes", Json::string(&instruction.bytes)),
        ("text", Json::string(&instruction.text)),
        (
            "sampleCount",
            json_u64(instruction.sample_count, "sample count")?,
        ),
        ("periodSum", json_u64(instruction.period_sum, "period sum")?),
    ]))
}

fn write_ida_outputs(
    output: &RunDirectory,
    function: &Function,
    capture: &Capture,
    ida_input: &Path,
    requested: u64,
) -> Result<(), String> {
    let instructions = function
        .instructions
        .iter()
        .map(|instruction| {
            Ok(Json::object([
                (
                    "address",
                    Json::string(format!("0x{:x}", instruction.address)),
                ),
                ("size", json_u64(instruction.size, "instruction size")?),
                ("bytes", Json::string(&instruction.bytes)),
                ("text", Json::string(&instruction.text)),
            ]))
        })
        .collect::<Result<Vec<_>, String>>()?;
    output.write_new(
        "ida/disassembly.json",
        &Json::Array(instructions).to_python_json(),
    )?;
    output.write_new("ida/pseudocode.c", &format!("{}\n", function.pseudocode))?;
    let summary = Json::object([
        ("schemaVersion", Json::Int(2)),
        ("inputFile", Json::string(ida_input.display().to_string())),
        ("inputSha256", Json::string(&capture.binary_sha256)),
        ("requestedAddress", Json::string(format!("0x{requested:x}"))),
        (
            "function",
            Json::object([
                ("name", Json::string(&function.name)),
                ("start", Json::string(format!("0x{:x}", function.start))),
                ("end", Json::string(format!("0x{:x}", function.end))),
                (
                    "size",
                    json_u64(function.end - function.start, "function size")?,
                ),
                (
                    "instructionCount",
                    json_u64(
                        u64::try_from(function.instructions.len())
                            .map_err(|error| error.to_string())?,
                        "instruction count",
                    )?,
                ),
            ]),
        ),
    ]);
    output.write_new("ida/summary.json", &summary.to_python_json())?;
    Ok(())
}

fn dso_basename(path: &str) -> Option<&str> {
    let trimmed = path.trim_matches(|character| matches!(character, '(' | ')' | '[' | ']'));
    Path::new(trimmed).file_name()?.to_str()
}

fn select_samples(
    events: &str,
    raw_symbol: &str,
    expected_dso: &str,
) -> Result<Vec<Sample>, String> {
    let prefix = format!("{raw_symbol}+0x");
    let mut samples = Vec::new();
    for line in events.lines() {
        let parts = line.split_whitespace().collect::<Vec<_>>();
        if parts.len() != 4 || !parts[2].starts_with(&prefix) {
            continue;
        }
        if dso_basename(parts[3]) != Some(expected_dso) {
            continue;
        }
        let offset_text = &parts[2][prefix.len()..];
        if offset_text.is_empty() || !offset_text.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            continue;
        }
        let period = parts[0]
            .parse::<u64>()
            .map_err(|error| format!("invalid perf sample period in {line:?}: {error}"))?;
        if period == 0 {
            return Err(format!("non-positive perf sample period in {line:?}"));
        }
        let offset = u64::from_str_radix(offset_text, 16)
            .map_err(|error| format!("invalid perf symbol offset in {line:?}: {error}"))?;
        samples.push(Sample {
            period,
            offset,
            source: line.trim().to_owned(),
        });
    }
    if samples.is_empty() {
        return Err(format!(
            "no perf samples resolved to {raw_symbol} in {expected_dso}"
        ));
    }
    Ok(samples)
}

fn add(total: &mut u64, value: u64, context: &str) -> Result<(), String> {
    *total = total
        .checked_add(value)
        .ok_or_else(|| format!("{context} overflow"))?;
    Ok(())
}

fn map_samples(function: &mut Function, samples: &[Sample]) -> Result<Totals, String> {
    let mut totals = Totals::default();
    for sample in samples {
        add(&mut totals.sample_rows, 1, "sample row count")?;
        add(&mut totals.period_sum, sample.period, "sample period sum")?;
        let Some(address) = function.start.checked_add(sample.offset) else {
            add(&mut totals.unmapped_rows, 1, "unmapped row count")?;
            add(
                &mut totals.unmapped_period,
                sample.period,
                "unmapped period sum",
            )?;
            continue;
        };
        let index = function
            .instructions
            .partition_point(|instruction| instruction.address <= address);
        let mapped = index.checked_sub(1).and_then(|position| {
            let instruction = &function.instructions[position];
            (address < function.end
                && address >= instruction.address
                && address < instruction.address + instruction.size)
                .then_some(position)
        });
        if let Some(position) = mapped {
            let instruction = &mut function.instructions[position];
            add(&mut instruction.sample_count, 1, "instruction sample count")?;
            add(
                &mut instruction.period_sum,
                sample.period,
                "instruction period sum",
            )?;
            add(&mut totals.mapped_rows, 1, "mapped row count")?;
            add(
                &mut totals.mapped_period,
                sample.period,
                "mapped period sum",
            )?;
        } else {
            add(&mut totals.unmapped_rows, 1, "unmapped row count")?;
            add(
                &mut totals.unmapped_period,
                sample.period,
                "unmapped period sum",
            )?;
        }
    }
    if totals.sample_rows == 0 || totals.mapped_rows == 0 {
        return Err("perf sample file contains no mapped samples".to_owned());
    }
    Ok(totals)
}

fn sampled_order(left: &Instruction, right: &Instruction) -> Ordering {
    right
        .period_sum
        .cmp(&left.period_sum)
        .then_with(|| right.sample_count.cmp(&left.sample_count))
        .then_with(|| left.address.cmp(&right.address))
}

fn totals_json(totals: &Totals, unmapped_percent: f64) -> Result<Json, String> {
    Ok(Json::object([
        ("sampleRows", json_u64(totals.sample_rows, "sample rows")?),
        ("periodSum", json_u64(totals.period_sum, "period sum")?),
        ("mappedRows", json_u64(totals.mapped_rows, "mapped rows")?),
        (
            "mappedPeriod",
            json_u64(totals.mapped_period, "mapped period")?,
        ),
        (
            "unmappedRows",
            json_u64(totals.unmapped_rows, "unmapped rows")?,
        ),
        (
            "unmappedPeriod",
            json_u64(totals.unmapped_period, "unmapped period")?,
        ),
        ("unmappedPeriodPercent", Json::Float(unmapped_percent)),
    ]))
}

fn aggregate(
    output: &RunDirectory,
    function: &mut Function,
    samples: &[Sample],
    capture: &Capture,
    expected_dso: &str,
    plan: &Plan,
) -> Result<(Totals, f64), String> {
    let totals = map_samples(function, samples)?;
    let unmapped_percent = totals.unmapped_period as f64 * 100.0 / totals.period_sum as f64;
    if unmapped_percent >= HARD_UNMAPPED_PERCENT {
        return Err(format!(
            "unmapped perf period {unmapped_percent:.6}% is not below the 1% hard gate"
        ));
    }
    if unmapped_percent > plan.max_unmapped_period_percent {
        return Err(format!(
            "unmapped perf period {unmapped_percent:.6}% exceeds the reviewed {:.6}% gate",
            plan.max_unmapped_period_percent
        ));
    }
    let mut ranked_instructions = function
        .instructions
        .iter()
        .filter(|instruction| instruction.sample_count > 0)
        .collect::<Vec<_>>();
    ranked_instructions.sort_by(|left, right| sampled_order(left, right));

    let instruction_rows = ranked_instructions
        .iter()
        .enumerate()
        .map(|(index, instruction)| {
            let Json::Object(mut row) = instruction_json(instruction, function.start)? else {
                unreachable!("instruction JSON is an object");
            };
            row.insert(
                "rank".to_owned(),
                json_u64(
                    u64::try_from(index + 1).map_err(|error| error.to_string())?,
                    "rank",
                )?,
            );
            row.insert(
                "samplePercent".to_owned(),
                Json::Float(instruction.sample_count as f64 * 100.0 / totals.mapped_rows as f64),
            );
            row.insert(
                "periodPercent".to_owned(),
                Json::Float(instruction.period_sum as f64 * 100.0 / totals.mapped_period as f64),
            );
            Ok(Json::Object(row))
        })
        .collect::<Result<Vec<_>, String>>()?;
    let explanation = plan
        .unmapped_period_explanation
        .as_deref()
        .map_or(Json::Null, Json::string);
    let report = Json::object([
        ("schemaVersion", Json::Int(2)),
        (
            "identity",
            Json::object([
                ("binary_sha256", Json::string(&capture.binary_sha256)),
                ("binary_build_id", Json::string(&capture.binary_build_id)),
                ("raw_symbol", Json::string(&function.name)),
                ("dso_basename", Json::string(expected_dso)),
            ]),
        ),
        (
            "mappingGate",
            Json::object([
                (
                    "maxUnmappedPeriodPercent",
                    Json::Float(plan.max_unmapped_period_percent),
                ),
                (
                    "hardMaximumPercentExclusive",
                    Json::Float(HARD_UNMAPPED_PERCENT),
                ),
                ("unmappedPeriodExplanation", explanation),
            ]),
        ),
        (
            "function",
            Json::object([
                ("name", Json::string(&function.name)),
                ("start", Json::string(format!("0x{:x}", function.start))),
                ("end", Json::string(format!("0x{:x}", function.end))),
                (
                    "size",
                    json_u64(function.end - function.start, "function size")?,
                ),
                (
                    "instructionCount",
                    json_u64(
                        u64::try_from(function.instructions.len())
                            .map_err(|error| error.to_string())?,
                        "instruction count",
                    )?,
                ),
                (
                    "sampledInstructionCount",
                    json_u64(
                        u64::try_from(ranked_instructions.len())
                            .map_err(|error| error.to_string())?,
                        "sampled instruction count",
                    )?,
                ),
            ]),
        ),
        ("totals", totals_json(&totals, unmapped_percent)?),
        ("instructions", Json::Array(instruction_rows)),
    ]);
    output.write_new("instruction-hotspots.json", &report.to_python_json())?;

    let mut tsv = String::from(
        "rank\tperiod_percent\tsample_percent\tperiod_sum\tsample_count\taddress\toffset\tsize\tbytes\tinstruction\n",
    );
    for (index, instruction) in ranked_instructions.iter().enumerate() {
        let text = instruction.text.replace('\t', " ");
        let _ = writeln!(
            tsv,
            "{}\t{:.6}\t{:.6}\t{}\t{}\t0x{:x}\t0x{:x}\t{}\t{}\t{}",
            index + 1,
            instruction.period_sum as f64 * 100.0 / totals.mapped_period as f64,
            instruction.sample_count as f64 * 100.0 / totals.mapped_rows as f64,
            instruction.period_sum,
            instruction.sample_count,
            instruction.address,
            instruction.address - function.start,
            instruction.size,
            instruction.bytes,
            text
        );
    }
    output.write_new("instruction-hotspots.tsv", &tsv)?;

    let mut text = format!(
        "Function: {}\nSamples: {}/{} mapped\nUnmapped period: {:.6}%\n\nRank  Period%  Samples  Address     Offset   Instruction\n",
        function.name, totals.mapped_rows, totals.sample_rows, unmapped_percent
    );
    for (index, instruction) in ranked_instructions.iter().take(40).enumerate() {
        let _ = writeln!(
            text,
            "{:>4}  {:>7.3}  {:>7}  {:>10}  {:>7}  {}",
            index + 1,
            instruction.period_sum as f64 * 100.0 / totals.mapped_period as f64,
            instruction.sample_count,
            format!("0x{:x}", instruction.address),
            format!("0x{:x}", instruction.address - function.start),
            instruction.text
        );
    }
    output.write_new("instruction-hotspots.txt", &text)?;
    Ok((totals, unmapped_percent))
}

fn make_private_directory(path: &Path) -> Result<(), String> {
    std::fs::DirBuilder::new()
        .mode(0o700)
        .create(path)
        .map_err(|error| format!("could not create {}: {error}", path.display()))
}

fn write_tool_capture(
    output: &RunDirectory,
    stdout_name: &str,
    stderr_name: &str,
    outcome: &crate::process::Outcome,
) -> Result<(), String> {
    output.write_new(stdout_name, &outcome.stdout)?;
    output.write_new(stderr_name, &outcome.stderr)?;
    Ok(())
}

fn execute(plan: &Plan, capture: &Capture, output: &RunDirectory) -> Result<(), String> {
    let requested = parse_address(&plan.address, "--address")?;
    make_private_directory(&output.join("ida"))?;
    make_private_directory(&output.join("ida-work"))?;

    let binary_name = capture
        .binary
        .file_name()
        .ok_or_else(|| "archived binary has no file name".to_owned())?;
    let ida_input = output.join("ida-work").join(binary_name);
    std::fs::copy(&capture.binary, &ida_input).map_err(|error| {
        format!(
            "could not isolate archived binary {}: {error}",
            capture.binary.display()
        )
    })?;
    let mut permissions = ida_input
        .metadata()
        .map_err(|error| format!("could not stat isolated IDA input: {error}"))?
        .permissions();
    permissions.set_mode(permissions.mode() & !0o222);
    std::fs::set_permissions(&ida_input, permissions)
        .map_err(|error| format!("could not make IDA input read-only: {error}"))?;
    if hash::sha256_file(&ida_input)? != capture.binary_sha256 {
        return Err("isolated IDA input SHA-256 mismatch".to_owned());
    }

    let bridge = output.join("ida-work/idalib-bridge.py");
    write_new(&bridge, IDALIB_BRIDGE.as_bytes())?;
    let dwarf = Tool::new("addr2line")
        .args([
            "-e".to_owned(),
            capture.binary.display().to_string(),
            "-f".to_owned(),
            "-C".to_owned(),
            "-i".to_owned(),
            format!("0x{requested:x}"),
        ])
        .probe()
        .map_err(|error| format!("addr2line could not start: {error}"))?;
    write_tool_capture(output, "dwarf.txt", "dwarf.stderr", &dwarf)?;
    if !dwarf.success() {
        return Err(format!(
            "addr2line failed with exit code {}",
            dwarf.code.unwrap_or(128)
        ));
    }

    let raw_result = output.join("ida-work/result.json");
    let idalib = Tool::new("timeout")
        .args([
            "-k".to_owned(),
            "5s".to_owned(),
            format!("{}s", plan.timeout_seconds),
            plan.idalib_python.display().to_string(),
            bridge.display().to_string(),
            ida_input.display().to_string(),
            format!("0x{requested:x}"),
            raw_result.display().to_string(),
        ])
        .probe()
        .map_err(|error| format!("IDALib could not start: {error}"))?;
    write_tool_capture(
        output,
        "ida-work/idalib.stdout",
        "ida-work/idalib.stderr",
        &idalib,
    )?;
    if !idalib.success() {
        return Err(format!(
            "IDALib failed with exit code {}; see {}",
            idalib.code.unwrap_or(128),
            output.join("ida-work/idalib.stderr").display()
        ));
    }
    regular_not_symlink(&raw_result, "IDALib bridge result")?;
    if hash::sha256_file(&ida_input)? != capture.binary_sha256 {
        return Err("isolated IDA input changed during analysis".to_owned());
    }
    let mut function = parse_idalib_result(&raw_result, requested)?;
    write_ida_outputs(output, &function, capture, &ida_input, requested)?;

    run_stdout_file(
        Path::new("llvm-objdump"),
        &[
            "--disassemble".to_owned(),
            "--demangle".to_owned(),
            "--source".to_owned(),
            "--line-numbers".to_owned(),
            "-M".to_owned(),
            "intel".to_owned(),
            format!("--start-address=0x{:x}", function.start),
            format!("--stop-address=0x{:x}", function.end),
            capture.binary.display().to_string(),
        ],
        &output.join("llvm-disassembly.txt"),
        &output.join("llvm-disassembly.stderr"),
    )?;

    let buildids = Tool::new("perf")
        .args([
            "buildid-list".to_owned(),
            "-i".to_owned(),
            capture.perf_data.display().to_string(),
        ])
        .run()
        .map_err(|error| format!("perf buildid-list failed: {error}"))?;
    if !buildids
        .stdout
        .to_ascii_lowercase()
        .contains(&capture.binary_build_id)
    {
        return Err(format!(
            "perf data does not contain binary Build ID {}",
            capture.binary_build_id
        ));
    }
    output.write_new("perf-buildids.txt", &buildids.stdout)?;

    run_stdout_file(
        Path::new("perf"),
        &[
            "script".to_owned(),
            "-G".to_owned(),
            "--no-demangle".to_owned(),
            "-i".to_owned(),
            capture.perf_data.display().to_string(),
            "-F".to_owned(),
            "hw:ip,sym,symoff,period,dso".to_owned(),
        ],
        &output.join("perf-script-events.txt"),
        &output.join("perf-script-events.stderr"),
    )?;
    let events = std::fs::read_to_string(output.join("perf-script-events.txt"))
        .map_err(|error| format!("could not read perf script events: {error}"))?;
    let expected_dso = binary_name
        .to_str()
        .ok_or_else(|| "archived binary file name is not UTF-8".to_owned())?;
    let samples = select_samples(&events, &function.name, expected_dso)?;
    let mut sample_text = format!(
        "# binary_sha256={}\n# binary_build_id={}\n# raw_symbol={}\n# dso_basename={}\n# fields=period ip raw_symbol+offset dso\n",
        capture.binary_sha256, capture.binary_build_id, function.name, expected_dso
    );
    for sample in &samples {
        let _ = writeln!(sample_text, "{}", sample.source);
    }
    output.write_new("perf-symbol-samples.txt", &sample_text)?;
    let (totals, unmapped_percent) =
        aggregate(output, &mut function, &samples, capture, expected_dso, plan)?;

    let metadata = Json::object([
        ("schemaVersion", Json::Int(2)),
        ("state", Json::string("COMPLETE")),
        ("label", Json::string(&plan.label)),
        (
            "requestedStaticAddress",
            Json::string(format!("0x{requested:x}")),
        ),
        (
            "capture",
            Json::object([
                ("runId", Json::string(&capture.run_id)),
                (
                    "runDirectory",
                    Json::string(capture.root.display().to_string()),
                ),
                ("binary", Json::string(capture.binary.display().to_string())),
                ("binarySha256", Json::string(&capture.binary_sha256)),
                ("binaryBuildId", Json::string(&capture.binary_build_id)),
                (
                    "perfData",
                    Json::string(capture.perf_data.display().to_string()),
                ),
                (
                    "perfDataSha256",
                    Json::string(hash::sha256_file(&capture.perf_data)?),
                ),
            ]),
        ),
        (
            "idalib",
            Json::object([
                (
                    "python",
                    Json::string(plan.idalib_python.display().to_string()),
                ),
                ("bridgeSha256", Json::string(hash::sha256_file(&bridge)?)),
                (
                    "timeoutSeconds",
                    json_u64(plan.timeout_seconds, "IDALib timeout")?,
                ),
                ("boundary", Json::string("generated-direct-api-bridge")),
            ]),
        ),
        (
            "function",
            Json::object([
                ("name", Json::string(&function.name)),
                ("start", Json::string(format!("0x{:x}", function.start))),
                ("end", Json::string(format!("0x{:x}", function.end))),
            ]),
        ),
        ("totals", totals_json(&totals, unmapped_percent)?),
    ]);
    output.write_new("metadata.json", &metadata.to_python_json())?;

    let primary_files = [
        "metadata.json",
        "dwarf.txt",
        "dwarf.stderr",
        "ida/summary.json",
        "ida/disassembly.json",
        "ida/pseudocode.c",
        "ida-work/idalib-bridge.py",
        "ida-work/result.json",
        "ida-work/idalib.stdout",
        "ida-work/idalib.stderr",
        "llvm-disassembly.txt",
        "llvm-disassembly.stderr",
        "perf-buildids.txt",
        "perf-script-events.txt",
        "perf-script-events.stderr",
        "perf-symbol-samples.txt",
        "instruction-hotspots.json",
        "instruction-hotspots.tsv",
        "instruction-hotspots.txt",
    ];
    let mut sums = String::new();
    let mut file_rows = Vec::with_capacity(primary_files.len());
    for relative in primary_files {
        let digest = hash::sha256_file(&output.join(relative))?;
        let _ = writeln!(sums, "{digest}  {relative}");
        file_rows.push(Json::object([
            ("path", Json::string(relative)),
            ("sha256", Json::string(digest)),
        ]));
    }
    output.write_new("SHA256SUMS", &sums)?;
    let contract = Json::object([
        ("schemaVersion", Json::Int(1)),
        ("state", Json::string("COMPLETE")),
        ("collector", Json::string("perf-hotspot-bundle")),
        ("runId", Json::string(&capture.run_id)),
        ("label", Json::string(&plan.label)),
        ("binarySha256", Json::string(&capture.binary_sha256)),
        ("binaryBuildId", Json::string(&capture.binary_build_id)),
        ("files", Json::Array(file_rows)),
        (
            "sha256sumsSha256",
            Json::string(hash::sha256_file(&output.join("SHA256SUMS"))?),
        ),
    ]);
    output.write_new("bundle-contract.json", &contract.to_python_json())?;
    publication::publish_success_marker(
        &output.join("bundle-completion.json"),
        &output.join("bundle-contract.json"),
        &format!("{}:{}", capture.run_id, plan.label),
        "perf-hotspot-bundle",
    )?;
    Ok(())
}

/// Exports and publishes one instruction-level hotspot bundle.
///
/// # Errors
///
/// Returns an argument, capture-identity, external-mechanism, mapping-gate or
/// publication diagnostic. Once created, an incomplete output is marked
/// `FAILED` and is never silently reused.
pub fn run(plan: &Plan) -> Result<String, String> {
    validate(plan)?;
    for program in ["addr2line", "llvm-objdump", "perf", "readelf", "timeout"] {
        if !Tool::exists(program) {
            return Err(format!("required tool unavailable: {program}"));
        }
    }
    let capture = load_capture(plan)?;
    let hotspots = capture.root.join("hotspots");
    match hotspots.symlink_metadata() {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_dir() => {
            return Err(format!(
                "hotspots path is not a non-symlink directory: {}",
                hotspots.display()
            ));
        }
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            make_private_directory(&hotspots)?;
        }
        Err(error) => {
            return Err(format!("could not inspect {}: {error}", hotspots.display()));
        }
    }
    let hotspot = hotspots.join(&plan.label);
    let output = RunDirectory::create(&hotspot)?;
    if let Err(error) = execute(plan, &capture, &output) {
        let failure = Json::object([
            ("schemaVersion", Json::Int(1)),
            ("state", Json::string("FAILED")),
            ("label", Json::string(&plan.label)),
            ("error", Json::string(&error)),
        ]);
        let _ = output.write_new("FAILED.json", &failure.to_python_json());
        return Err(error);
    }
    Ok(format!("hotspot bundle complete: {}", hotspot.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!("rr-hotspot-bundle-{}-{name}", std::process::id()))
    }

    fn fixture_function() -> Function {
        Function {
            name: "raw_symbol".to_owned(),
            start: 0x1000,
            end: 0x1004,
            instructions: vec![
                Instruction {
                    address: 0x1000,
                    size: 2,
                    bytes: "9090".to_owned(),
                    text: "nop".to_owned(),
                    sample_count: 0,
                    period_sum: 0,
                },
                Instruction {
                    address: 0x1002,
                    size: 2,
                    bytes: "c3cc".to_owned(),
                    text: "ret".to_owned(),
                    sample_count: 0,
                    period_sum: 0,
                },
            ],
            pseudocode: "return;".to_owned(),
        }
    }

    #[test]
    fn bridge_result_is_validated_before_policy_uses_it() {
        let path = scratch("idalib.json");
        let _ = std::fs::remove_file(&path);
        std::fs::write(
            &path,
            r#"{"requestedAddress":"0x1001","function":{"name":"raw_symbol","start":"0x1000","end":"0x1004"},"instructions":[{"address":"0x1000","size":2,"bytes":"9090","text":"nop"},{"address":"0x1002","size":2,"bytes":"c3cc","text":"ret"}],"pseudocode":"return;"}"#,
        )
        .unwrap();
        let function = parse_idalib_result(&path, 0x1001).expect("valid fixture");
        assert_eq!(function.instructions.len(), 2);
        assert!(parse_idalib_result(&path, 0x1002).is_err());
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn symbol_selection_is_identity_exact() {
        let events = concat!(
            "1000 0x1 raw_symbol+0x0 (/tmp/rust-reality)\n",
            "3000 0x3 raw_symbol+0x3 (/tmp/rust-reality)\n",
            "10 0x1 other+0x0 (/tmp/rust-reality)\n",
            "10 0x1 raw_symbol+0x0 (/tmp/other)\n",
        );
        let samples = select_samples(events, "raw_symbol", "rust-reality").unwrap();
        assert_eq!(samples.len(), 2);
        assert_eq!(samples[1].offset, 3);
    }

    #[test]
    fn instruction_mapping_matches_the_legacy_boundaries() {
        let mut function = fixture_function();
        let samples = vec![
            Sample {
                period: 1000,
                offset: 0,
                source: String::new(),
            },
            Sample {
                period: 3000,
                offset: 3,
                source: String::new(),
            },
        ];
        let totals = map_samples(&mut function, &samples).unwrap();
        assert_eq!(totals.mapped_rows, 2);
        assert_eq!(function.instructions[1].period_sum, 3000);
    }

    #[test]
    fn unmapped_samples_remain_visible_to_the_hard_gate() {
        let mut function = fixture_function();
        let samples = vec![
            Sample {
                period: 9900,
                offset: 0,
                source: String::new(),
            },
            Sample {
                period: 100,
                offset: 5,
                source: String::new(),
            },
        ];
        let totals = map_samples(&mut function, &samples).unwrap();
        let percent = totals.unmapped_period as f64 * 100.0 / totals.period_sum as f64;
        assert!((percent - 1.0).abs() < f64::EPSILON);
        assert!(percent >= HARD_UNMAPPED_PERCENT);
    }

    #[test]
    fn bounded_identifiers_and_thresholds_are_enforced() {
        assert!(safe_component("dispatch-loop_1.0"));
        assert!(!safe_component("../escape"));
        assert!(parse_address("0xdeadbeef", "address").is_ok());
        assert!(parse_address("deadbeef", "address").is_err());
        assert!(!valid_lower_hex("ABC", None));
    }
}
