//! Native hotspot bundle export and instruction aggregation.
//!
//! Rust owns the input path, capture identity, `IDALib` isolation, output schema,
//! sample mapping gates, checksums, failure state and publication. `IDALib` exposes
//! its automation API through Python, so the only Python retained here is a
//! generated private bridge containing direct IDA API calls. It has no argument,
//! path, identity, verdict or publication policy of its own.

#![allow(
    clippy::cast_precision_loss,
    clippy::too_many_lines,
    reason = "the bounded export lifecycle and evidence schemas are intentionally explicit"
)]

use std::{
    cmp::Ordering,
    fmt::Write as _,
    fs::OpenOptions,
    io::Write as _,
    os::unix::fs::{DirBuilderExt as _, PermissionsExt as _},
    path::{Path, PathBuf},
    process::{Command, Stdio},
};

use crate::{
    bench::{attest, evidence::RunDirectory, publication},
    hash,
    perf::{json_in, json_out::Json},
    process::Tool,
};

const MAX_TIMEOUT_SECONDS: u64 = 1_800;
const MAX_PERF_DATA_BYTES: u64 = 1024 * 1024 * 1024;
const MAX_FUNCTION_BYTES: u64 = 64 * 1024 * 1024;
const MAX_INSTRUCTIONS: usize = 4_000_000;
const HARD_UNMAPPED_PERCENT: f64 = 1.0;

const IDALIB_BRIDGE: &str = r#"# Generated by rr-dev. IDALib requires this import to be first.
import idapro
import json
import sys
import traceback

import ida_auto
import ida_bytes
import ida_funcs
import ida_hexrays
import ida_lines
import ida_name
import ida_ua


def main():
    input_path, address_text, output_path = sys.argv[1:]
    requested = int(address_text, 0)
    result = idapro.open_database(input_path, True)
    if result != 0:
        raise RuntimeError(f"idapro.open_database failed with code {result}")
    try:
        if not ida_auto.auto_wait():
            raise RuntimeError("IDA auto-analysis was cancelled")
        function = ida_funcs.get_func(requested)
        if function is None:
            raise RuntimeError(f"no IDA function contains 0x{requested:x}")
        start = function.start_ea
        end = function.end_ea
        instructions = []
        address = start
        while address < end:
            instruction = ida_ua.insn_t()
            size = ida_ua.decode_insn(instruction, address)
            if size <= 0:
                address += 1
                continue
            raw = ida_bytes.get_bytes(address, size) or b""
            text = ida_lines.generate_disasm_line(
                address, ida_lines.GENDSM_REMOVE_TAGS
            )
            instructions.append({
                "address": f"0x{address:x}",
                "size": size,
                "bytes": raw.hex(),
                "text": text or "",
            })
            address += size
        if not ida_hexrays.init_hexrays_plugin():
            raise RuntimeError("Hex-Rays Decompiler is unavailable")
        cfunc = ida_hexrays.decompile(start)
        if cfunc is None:
            raise RuntimeError(f"Hex-Rays failed to decompile 0x{start:x}")
        pseudocode = "\n".join(
            ida_lines.tag_remove(line.line) for line in cfunc.get_pseudocode()
        )
        result = {
            "requestedAddress": f"0x{requested:x}",
            "function": {
                "name": ida_name.get_ea_name(start),
                "start": f"0x{start:x}",
                "end": f"0x{end:x}",
            },
            "instructions": instructions,
            "pseudocode": pseudocode,
        }
        with open(output_path, "x", encoding="utf-8") as output:
            json.dump(result, output, ensure_ascii=False, separators=(",", ":"))
            output.write("\n")
    finally:
        idapro.close_database()


if __name__ == "__main__":
    try:
        main()
    except Exception:
        traceback.print_exc()
        raise SystemExit(1)
"#;

/// One export request rooted in a completed native hotspot capture.
#[derive(Debug, Clone)]
pub struct Plan {
    /// Completed `cargo dev perf hotspot` run directory.
    pub run_dir: PathBuf,
    /// Safe evidence label.
    pub label: String,
    /// Perf DSO/file offset to normalize through the executable ELF `PT_LOAD`.
    pub dso_offset: String,
    /// `IDALib` Python executable.
    pub idalib_python: PathBuf,
    /// `IDALib` timeout.
    pub timeout_seconds: u64,
    /// Reviewed soft threshold below the hard one-percent gate.
    pub max_unmapped_period_percent: f64,
    /// Explanation required for a non-zero threshold.
    pub unmapped_period_explanation: Option<String>,
}

#[derive(Debug)]
struct Capture {
    root: PathBuf,
    run_id: String,
    binary: PathBuf,
    binary_sha256: String,
    binary_build_id: String,
    perf_data: PathBuf,
    perf_data_sha256: String,
}

#[derive(Debug, Clone)]
struct Instruction {
    address: u64,
    size: u64,
    bytes: String,
    text: String,
    sample_count: u64,
    period_sum: u64,
}

#[derive(Debug)]
struct Function {
    name: String,
    start: u64,
    end: u64,
    instructions: Vec<Instruction>,
    pseudocode: String,
}

#[derive(Debug)]
struct Sample {
    period: u64,
    runtime_ip: u64,
    dso_offset: u64,
    static_address: u64,
    source: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct LoadSegment {
    file_offset: u64,
    virtual_address: u64,
    file_size: u64,
    memory_size: u64,
    alignment: u64,
    flags: u32,
}

impl LoadSegment {
    const fn executable(self) -> bool {
        self.flags & 1 != 0
    }
}

#[derive(Debug)]
struct ElfAddressMap {
    loads: Vec<LoadSegment>,
}

#[derive(Debug, Default)]
struct SelectionTotals {
    dso_rows: u64,
    dso_period: u64,
    function_rows: u64,
    function_period: u64,
    outside_function_rows: u64,
    outside_function_period: u64,
    runtime_base: Option<u64>,
}

#[derive(Debug, Default)]
struct Totals {
    sample_rows: u64,
    period_sum: u64,
    mapped_rows: u64,
    mapped_period: u64,
    unmapped_rows: u64,
    unmapped_period: u64,
}

fn read_array<const N: usize>(
    bytes: &[u8],
    offset: usize,
    context: &str,
) -> Result<[u8; N], String> {
    let end = offset
        .checked_add(N)
        .ok_or_else(|| format!("{context} offset overflow"))?;
    bytes
        .get(offset..end)
        .ok_or_else(|| format!("truncated {context}"))?
        .try_into()
        .map_err(|_| format!("invalid {context}"))
}

fn elf_u16(bytes: &[u8], offset: usize, context: &str) -> Result<u16, String> {
    Ok(u16::from_le_bytes(read_array(bytes, offset, context)?))
}

fn elf_u32(bytes: &[u8], offset: usize, context: &str) -> Result<u32, String> {
    Ok(u32::from_le_bytes(read_array(bytes, offset, context)?))
}

fn elf_u64(bytes: &[u8], offset: usize, context: &str) -> Result<u64, String> {
    Ok(u64::from_le_bytes(read_array(bytes, offset, context)?))
}

impl ElfAddressMap {
    fn parse(binary: &Path) -> Result<Self, String> {
        let bytes = std::fs::read(binary)
            .map_err(|error| format!("could not read ELF {}: {error}", binary.display()))?;
        if bytes.get(..4) != Some(b"\x7fELF")
            || bytes.get(4) != Some(&2)
            || bytes.get(5) != Some(&1)
            || bytes.get(6) != Some(&1)
        {
            return Err("hotspot bundle requires a little-endian ELF64 binary".to_owned());
        }
        let elf_type = elf_u16(&bytes, 16, "ELF type")?;
        let machine = elf_u16(&bytes, 18, "ELF machine")?;
        if !matches!(elf_type, 2 | 3) || machine != 62 || elf_u32(&bytes, 20, "ELF version")? != 1 {
            return Err("hotspot bundle requires an x86-64 ET_EXEC or ET_DYN ELF".to_owned());
        }
        let program_offset = elf_u64(&bytes, 32, "program-header table offset")?;
        let header_size = elf_u16(&bytes, 52, "ELF header size")?;
        let entry_size = elf_u16(&bytes, 54, "program-header entry size")?;
        let entry_count = elf_u16(&bytes, 56, "program-header entry count")?;
        if header_size < 64 || entry_size < 56 || entry_count == 0 || entry_count == u16::MAX {
            return Err("ELF program-header table is unsupported or empty".to_owned());
        }
        let program_offset = usize::try_from(program_offset)
            .map_err(|_| "ELF program-header offset exceeds addressable memory".to_owned())?;
        let entry_size = usize::from(entry_size);
        let mut loads = Vec::new();
        for index in 0..usize::from(entry_count) {
            let offset = index
                .checked_mul(entry_size)
                .and_then(|value| program_offset.checked_add(value))
                .ok_or_else(|| "ELF program-header offset overflow".to_owned())?;
            let entry_end = offset
                .checked_add(entry_size)
                .ok_or_else(|| "ELF program-header range overflow".to_owned())?;
            let entry = bytes
                .get(offset..entry_end)
                .ok_or_else(|| "truncated ELF program-header table".to_owned())?;
            if elf_u32(entry, 0, "program-header type")? != 1 {
                continue;
            }
            let segment = LoadSegment {
                flags: elf_u32(entry, 4, "PT_LOAD flags")?,
                file_offset: elf_u64(entry, 8, "PT_LOAD file offset")?,
                virtual_address: elf_u64(entry, 16, "PT_LOAD virtual address")?,
                file_size: elf_u64(entry, 32, "PT_LOAD file size")?,
                memory_size: elf_u64(entry, 40, "PT_LOAD memory size")?,
                alignment: elf_u64(entry, 48, "PT_LOAD alignment")?,
            };
            let file_end = segment
                .file_offset
                .checked_add(segment.file_size)
                .ok_or_else(|| "PT_LOAD file range overflow".to_owned())?;
            let memory_end = segment
                .virtual_address
                .checked_add(segment.memory_size)
                .ok_or_else(|| "PT_LOAD memory range overflow".to_owned())?;
            if segment.file_size > segment.memory_size
                || file_end > u64::try_from(bytes.len()).map_err(|error| error.to_string())?
                || memory_end < segment.virtual_address
                || (segment.alignment > 1
                    && (!segment.alignment.is_power_of_two()
                        || segment.file_offset % segment.alignment
                            != segment.virtual_address % segment.alignment))
            {
                return Err("ELF contains an invalid PT_LOAD range".to_owned());
            }
            loads.push(segment);
        }
        if !loads
            .iter()
            .any(|segment| segment.executable() && segment.file_size > 0)
        {
            return Err("ELF has no file-backed executable PT_LOAD segment".to_owned());
        }
        Ok(Self { loads })
    }

    fn dso_offset_to_static(&self, dso_offset: u64) -> Result<u64, String> {
        let matches = self
            .loads
            .iter()
            .filter(|segment| {
                segment.executable()
                    && dso_offset >= segment.file_offset
                    && dso_offset - segment.file_offset < segment.file_size
            })
            .collect::<Vec<_>>();
        let [segment] = matches.as_slice() else {
            return Err(format!(
                "perf DSO offset 0x{dso_offset:x} is not in exactly one file-backed executable PT_LOAD"
            ));
        };
        segment
            .virtual_address
            .checked_add(dso_offset - segment.file_offset)
            .ok_or_else(|| "static ELF address overflow".to_owned())
    }

    fn static_to_dso_offset(&self, address: u64) -> Result<u64, String> {
        let matches = self
            .loads
            .iter()
            .filter(|segment| {
                segment.executable()
                    && address >= segment.virtual_address
                    && address - segment.virtual_address < segment.file_size
            })
            .collect::<Vec<_>>();
        let [segment] = matches.as_slice() else {
            return Err(format!(
                "static ELF address 0x{address:x} is not in exactly one file-backed executable PT_LOAD"
            ));
        };
        segment
            .file_offset
            .checked_add(address - segment.virtual_address)
            .ok_or_else(|| "perf DSO offset overflow".to_owned())
    }
}

fn safe_component(value: &str) -> bool {
    let mut bytes = value.bytes();
    bytes
        .next()
        .is_some_and(|byte| byte.is_ascii_alphanumeric())
        && value.len() <= 96
        && bytes.all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
}

fn parse_address(value: &str, context: &str) -> Result<u64, String> {
    let digits = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
        .ok_or_else(|| format!("{context} must be hexadecimal with a 0x prefix"))?;
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(format!("{context} must be hexadecimal with a 0x prefix"));
    }
    u64::from_str_radix(digits, 16).map_err(|error| format!("invalid {context}: {error}"))
}

fn valid_lower_hex(value: &str, length: Option<usize>) -> bool {
    length.is_none_or(|expected| value.len() == expected)
        && !value.is_empty()
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn regular_not_symlink(path: &Path, context: &str) -> Result<(), String> {
    let metadata = path
        .symlink_metadata()
        .map_err(|error| format!("could not stat {context} {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err(format!(
            "{context} is not a regular non-symlink file: {}",
            path.display()
        ));
    }
    Ok(())
}

/// Validates bounded arguments without invoking `IDALib` or perf.
///
/// # Errors
///
/// Returns one actionable argument diagnostic.
pub fn validate(plan: &Plan) -> Result<(), String> {
    if !plan.run_dir.is_absolute() {
        return Err("--run-dir must be absolute".to_owned());
    }
    if !safe_component(&plan.label) {
        return Err("--label must be a 1..=96 character safe identifier".to_owned());
    }
    parse_address(&plan.dso_offset, "--dso-offset")?;
    if !plan.idalib_python.is_absolute() {
        return Err("--idalib-python must be absolute".to_owned());
    }
    regular_not_symlink(&plan.idalib_python, "IDALib Python")?;
    let mode = plan
        .idalib_python
        .metadata()
        .map_err(|error| format!("could not stat IDALib Python: {error}"))?
        .permissions()
        .mode();
    if mode & 0o111 == 0 {
        return Err("--idalib-python must be executable".to_owned());
    }
    if plan.timeout_seconds == 0 || plan.timeout_seconds > MAX_TIMEOUT_SECONDS {
        return Err("--timeout-seconds must be in 1..=1800".to_owned());
    }
    if !plan.max_unmapped_period_percent.is_finite()
        || !(0.0..HARD_UNMAPPED_PERCENT).contains(&plan.max_unmapped_period_percent)
    {
        return Err("--max-unmapped-period-percent must be in [0, 1)".to_owned());
    }
    match (
        plan.max_unmapped_period_percent > 0.0,
        plan.unmapped_period_explanation
            .as_deref()
            .is_some_and(|value| !value.trim().is_empty()),
    ) {
        (true, false) => {
            return Err(
                "a non-zero mapping threshold requires --unmapped-period-explanation".to_owned(),
            );
        }
        (false, true) => {
            return Err("an unmapped-period explanation requires a non-zero threshold".to_owned());
        }
        _ => {}
    }
    Ok(())
}

fn read_json(path: &Path, context: &str) -> Result<json_in::Value, String> {
    read_json_snapshot(path, context).map(|(value, _)| value)
}

fn read_json_snapshot(
    path: &Path,
    context: &str,
) -> Result<(json_in::Value, String), String> {
    let bytes = std::fs::read(path)
        .map_err(|error| format!("could not read {context} {}: {error}", path.display()))?;
    let text = std::str::from_utf8(&bytes)
        .map_err(|error| format!("invalid UTF-8 in {context} {}: {error}", path.display()))?;
    let value = json_in::parse(text)
        .map_err(|error| format!("invalid {context} {}: {error}", path.display()))?;
    Ok((value, crate::perf::loader::sha256_bytes(&bytes)))
}

fn load_capture(plan: &Plan) -> Result<Capture, String> {
    let root_metadata = plan.run_dir.symlink_metadata().map_err(|error| {
        format!(
            "could not stat --run-dir {}: {error}",
            plan.run_dir.display()
        )
    })?;
    if root_metadata.file_type().is_symlink() || !root_metadata.is_dir() {
        return Err("--run-dir must be an existing non-symlink directory".to_owned());
    }
    let root = plan
        .run_dir
        .canonicalize()
        .map_err(|error| format!("could not canonicalize --run-dir: {error}"))?;
    let metadata_path = root.join("metadata.json");
    let completion_path = root.join("run-completion.json");
    let contract_path = root.join("run-contract.json");
    let perf_data = root.join("perf.data");
    for (path, context) in [
        (&metadata_path, "hotspot metadata"),
        (&completion_path, "hotspot completion"),
        (&contract_path, "hotspot contract"),
        (&perf_data, "perf data"),
    ] {
        regular_not_symlink(path, context)?;
    }
    let (contract, contract_sha256) = read_json_snapshot(&contract_path, "hotspot contract")?;
    contract
        .require_int("hotspot contract", "schemaVersion", 2)
        .map_err(|_| {
            "hotspot contract is not hash-bound to perf.data; recapture with the current rr-dev"
                .to_owned()
        })?;
    contract
        .require_str("hotspot contract", "collector", "perf-hotspot")
        .map_err(|error| error.to_string())?;
    contract
        .require_str("hotspot contract", "phase", "complete")
        .map_err(|error| error.to_string())?;
    contract
        .require_int("hotspot contract", "exitCode", 0)
        .map_err(|error| error.to_string())?;
    let run_id = contract
        .str_field("hotspot contract", "runId")
        .map_err(|error| error.to_string())?
        .to_owned();
    if run_id.is_empty() {
        return Err("hotspot contract run ID is empty".to_owned());
    }
    let contract_binary = contract
        .field("hotspot contract", "binary")
        .map_err(|error| error.to_string())?;
    let binary_sha256 = contract_binary
        .str_field("hotspot contract.binary", "sha256")
        .map_err(|error| error.to_string())?
        .to_owned();
    let binary_build_id = contract_binary
        .str_field("hotspot contract.binary", "buildId")
        .map_err(|error| error.to_string())?
        .to_owned();
    if !valid_lower_hex(&binary_sha256, Some(64)) || !valid_lower_hex(&binary_build_id, None) {
        return Err("hotspot contract binary identity is malformed".to_owned());
    }
    let contract_perf_data = contract.optional("perfData").ok_or_else(|| {
        "hotspot contract does not bind perf.data; recapture with the current rr-dev".to_owned()
    })?;
    contract_perf_data
        .require_str("hotspot contract.perfData", "relativePath", "perf.data")
        .map_err(|error| error.to_string())?;
    let perf_data_sha256 = contract_perf_data
        .str_field("hotspot contract.perfData", "sha256")
        .map_err(|error| error.to_string())?
        .to_owned();
    if !valid_lower_hex(&perf_data_sha256, Some(64)) {
        return Err("hotspot contract perf.data identity is malformed".to_owned());
    }
    let completion = read_json(&completion_path, "hotspot completion")?;
    crate::perf::loader::verify_success_marker(
        &completion,
        &contract_path,
        &contract_sha256,
        &run_id,
        "perf-hotspot",
        "hotspot completion",
    )
    .map_err(|error| error.to_string())?;

    let metadata = read_json(&metadata_path, "hotspot metadata")?;
    metadata
        .require_str("metadata", "state", "COMPLETE")
        .map_err(|error| error.to_string())?;
    if metadata
        .str_field("metadata", "runId")
        .map_err(|error| error.to_string())?
        != run_id
        || metadata
            .str_field("metadata", "binarySha256")
            .map_err(|error| error.to_string())?
            != binary_sha256
        || metadata
            .str_field("metadata", "binaryBuildId")
            .map_err(|error| error.to_string())?
            != binary_build_id
    {
        return Err("hotspot metadata disagrees with the bound capture contract".to_owned());
    }

    let binary_dir = root.join("binary");
    let entries = std::fs::read_dir(&binary_dir)
        .map_err(|error| format!("could not read {}: {error}", binary_dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|error| format!("could not enumerate {}: {error}", binary_dir.display()))?;
    if entries.len() != 1 {
        return Err(format!(
            "hotspot capture must contain exactly one archived binary, found {}",
            entries.len()
        ));
    }
    let binary = entries[0].path();
    regular_not_symlink(&binary, "archived binary")?;
    if hash::sha256_file(&binary)? != binary_sha256 {
        return Err("archived binary SHA-256 does not match completed capture".to_owned());
    }
    if attest::build_id(&binary)? != binary_build_id {
        return Err("archived binary Build ID does not match completed capture".to_owned());
    }
    let perf_bytes = perf_data
        .metadata()
        .map_err(|error| format!("could not stat perf data: {error}"))?
        .len();
    if perf_bytes == 0 || perf_bytes > MAX_PERF_DATA_BYTES {
        return Err("perf data must be non-empty and no larger than 1 GiB".to_owned());
    }
    if hash::sha256_file(&perf_data)? != perf_data_sha256 {
        return Err("perf data SHA-256 does not match completed capture".to_owned());
    }
    Ok(Capture {
        root,
        run_id,
        binary,
        binary_sha256,
        binary_build_id,
        perf_data,
        perf_data_sha256,
    })
}

fn write_new(path: &Path, contents: &[u8]) -> Result<(), String> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| format!("could not create {}: {error}", path.display()))?;
    file.write_all(contents)
        .map_err(|error| format!("could not write {}: {error}", path.display()))?;
    file.sync_all()
        .map_err(|error| format!("could not sync {}: {error}", path.display()))
}

fn run_stdout_file(
    program: &Path,
    args: &[String],
    stdout: &Path,
    stderr: &Path,
) -> Result<(), String> {
    let stdout_file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(stdout)
        .map_err(|error| format!("could not create {}: {error}", stdout.display()))?;
    let stderr_file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(stderr)
        .map_err(|error| format!("could not create {}: {error}", stderr.display()))?;
    let status = Command::new(program)
        .args(args)
        .stdin(Stdio::null())
        .stdout(Stdio::from(stdout_file))
        .stderr(Stdio::from(stderr_file))
        .status()
        .map_err(|error| format!("could not run {}: {error}", program.display()))?;
    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "{} failed with {}; see {}",
            program.display(),
            status,
            stderr.display()
        ))
    }
}

fn json_u64(value: u64, context: &str) -> Result<Json, String> {
    i64::try_from(value)
        .map(Json::Int)
        .map_err(|_| format!("{context} exceeds the JSON integer range"))
}

fn parse_idalib_result(path: &Path, requested: u64) -> Result<Function, String> {
    let result = read_json(path, "IDALib bridge result")?;
    let observed_requested = parse_address(
        result
            .str_field("idalib", "requestedAddress")
            .map_err(|error| error.to_string())?,
        "IDALib requestedAddress",
    )?;
    if observed_requested != requested {
        return Err("IDALib returned a different requested address".to_owned());
    }
    let function = result
        .field("idalib", "function")
        .map_err(|error| error.to_string())?;
    let name = function
        .str_field("idalib.function", "name")
        .map_err(|error| error.to_string())?
        .to_owned();
    if name.is_empty() {
        return Err("IDALib returned an empty function name".to_owned());
    }
    let start = parse_address(
        function
            .str_field("idalib.function", "start")
            .map_err(|error| error.to_string())?,
        "IDALib function start",
    )?;
    let end = parse_address(
        function
            .str_field("idalib.function", "end")
            .map_err(|error| error.to_string())?,
        "IDALib function end",
    )?;
    if end <= start || requested < start || requested >= end || end - start > MAX_FUNCTION_BYTES {
        return Err("IDALib returned an invalid or oversized function range".to_owned());
    }
    let raw_instructions = result
        .array_field("idalib", "instructions")
        .map_err(|error| error.to_string())?;
    if raw_instructions.is_empty() || raw_instructions.len() > MAX_INSTRUCTIONS {
        return Err("IDALib returned an empty or oversized instruction list".to_owned());
    }
    let mut instructions = Vec::with_capacity(raw_instructions.len());
    for (index, raw) in raw_instructions.iter().enumerate() {
        let context = format!("idalib.instructions[{index}]");
        let address = parse_address(
            raw.str_field(&context, "address")
                .map_err(|error| error.to_string())?,
            &format!("{context}.address"),
        )?;
        let size = u64::try_from(
            raw.int_field(&context, "size")
                .map_err(|error| error.to_string())?,
        )
        .map_err(|_| format!("{context}.size must be positive"))?;
        let bytes = raw
            .str_field(&context, "bytes")
            .map_err(|error| error.to_string())?
            .to_owned();
        let text = raw
            .str_field(&context, "text")
            .map_err(|error| error.to_string())?
            .to_owned();
        let byte_length = usize::try_from(size)
            .ok()
            .and_then(|value| value.checked_mul(2));
        if size == 0
            || address < start
            || address >= end
            || address.checked_add(size).is_none_or(|last| last > end)
            || Some(bytes.len()) != byte_length
            || !bytes.bytes().all(|byte| byte.is_ascii_hexdigit())
        {
            return Err(format!("invalid IDALib instruction at index {index}"));
        }
        instructions.push(Instruction {
            address,
            size,
            bytes,
            text,
            sample_count: 0,
            period_sum: 0,
        });
    }
    instructions.sort_by_key(|instruction| instruction.address);
    for pair in instructions.windows(2) {
        if pair[0].address + pair[0].size > pair[1].address {
            return Err("IDALib instruction ranges overlap".to_owned());
        }
    }
    let pseudocode = result
        .str_field("idalib", "pseudocode")
        .map_err(|error| error.to_string())?
        .to_owned();
    if pseudocode.trim().is_empty() {
        return Err("IDALib returned empty pseudocode".to_owned());
    }
    Ok(Function {
        name,
        start,
        end,
        instructions,
        pseudocode,
    })
}

fn instruction_json(instruction: &Instruction, function_start: u64) -> Result<Json, String> {
    Ok(Json::object([
        (
            "address",
            Json::string(format!("0x{:x}", instruction.address)),
        ),
        (
            "offset",
            Json::string(format!("0x{:x}", instruction.address - function_start)),
        ),
        ("size", json_u64(instruction.size, "instruction size")?),
        ("bytes", Json::string(&instruction.bytes)),
        ("text", Json::string(&instruction.text)),
        (
            "sampleCount",
            json_u64(instruction.sample_count, "sample count")?,
        ),
        ("periodSum", json_u64(instruction.period_sum, "period sum")?),
    ]))
}

fn write_ida_outputs(
    output: &RunDirectory,
    function: &Function,
    capture: &Capture,
    ida_input: &Path,
    requested: u64,
) -> Result<(), String> {
    let instructions = function
        .instructions
        .iter()
        .map(|instruction| {
            Ok(Json::object([
                (
                    "address",
                    Json::string(format!("0x{:x}", instruction.address)),
                ),
                ("size", json_u64(instruction.size, "instruction size")?),
                ("bytes", Json::string(&instruction.bytes)),
                ("text", Json::string(&instruction.text)),
            ]))
        })
        .collect::<Result<Vec<_>, String>>()?;
    output.write_new(
        "ida/disassembly.json",
        &Json::Array(instructions).to_python_json(),
    )?;
    output.write_new("ida/pseudocode.c", &format!("{}\n", function.pseudocode))?;
    let summary = Json::object([
        ("schemaVersion", Json::Int(2)),
        ("inputFile", Json::string(ida_input.display().to_string())),
        ("inputSha256", Json::string(&capture.binary_sha256)),
        ("requestedAddress", Json::string(format!("0x{requested:x}"))),
        (
            "function",
            Json::object([
                ("name", Json::string(&function.name)),
                ("start", Json::string(format!("0x{:x}", function.start))),
                ("end", Json::string(format!("0x{:x}", function.end))),
                (
                    "size",
                    json_u64(function.end - function.start, "function size")?,
                ),
                (
                    "instructionCount",
                    json_u64(
                        u64::try_from(function.instructions.len())
                            .map_err(|error| error.to_string())?,
                        "instruction count",
                    )?,
                ),
            ]),
        ),
    ]);
    output.write_new("ida/summary.json", &summary.to_python_json())?;
    Ok(())
}

fn dso_basename(path: &str) -> Option<&str> {
    let trimmed = path.trim_matches(|character| matches!(character, '(' | ')' | '[' | ']'));
    Path::new(trimmed).file_name()?.to_str()
}

fn build_id_dso_path(
    buildids: &str,
    expected_build_id: &str,
    expected_basename: &str,
) -> Result<String, String> {
    let paths = buildids
        .lines()
        .filter_map(|line| {
            let mut fields = line.trim().splitn(2, char::is_whitespace);
            let build_id = fields.next()?;
            let path = fields.next()?.trim();
            (build_id == expected_build_id && !path.is_empty()).then(|| path.to_owned())
        })
        .collect::<Vec<_>>();
    let [path] = paths.as_slice() else {
        return Err(format!(
            "perf data must contain exactly one DSO path for Build ID {expected_build_id}, found {}",
            paths.len()
        ));
    };
    if dso_basename(path) != Some(expected_basename) {
        return Err(format!(
            "perf Build-ID DSO path does not name archived binary {expected_basename}"
        ));
    }
    Ok(path.clone())
}

fn parse_perf_hex(value: &str, context: &str) -> Result<u64, String> {
    let digits = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
        .unwrap_or(value);
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(format!("invalid {context}: {value:?}"));
    }
    u64::from_str_radix(digits, 16).map_err(|error| format!("invalid {context}: {error}"))
}

fn parse_perf_event(line: &str) -> Result<(u64, u64, &str, u64), String> {
    let trimmed = line.trim();
    let mut fields = trimmed.split_whitespace();
    let period_text = fields
        .next()
        .ok_or_else(|| format!("missing perf sample period in {line:?}"))?;
    let runtime_ip_text = fields
        .next()
        .ok_or_else(|| format!("missing perf runtime IP in {line:?}"))?;
    let dso_start = trimmed
        .find('(')
        .ok_or_else(|| format!("missing perf DSO-offset field in {line:?}"))?;
    let dso_field = trimmed
        .get(dso_start + 1..)
        .and_then(|value| value.strip_suffix(')'))
        .ok_or_else(|| format!("invalid perf DSO-offset field in {line:?}"))?;
    let (dso_path, dso_offset_text) = dso_field
        .rsplit_once("+0x")
        .ok_or_else(|| format!("missing perf DSO offset in {line:?}"))?;
    if dso_path.is_empty() {
        return Err(format!("empty perf DSO path in {line:?}"));
    }
    let period = period_text
        .parse::<u64>()
        .map_err(|error| format!("invalid perf sample period in {line:?}: {error}"))?;
    if period == 0 {
        return Err(format!("non-positive perf sample period in {line:?}"));
    }
    let runtime_ip = parse_perf_hex(runtime_ip_text, "perf runtime IP")?;
    let dso_offset = parse_perf_hex(dso_offset_text, "perf DSO offset")?;
    Ok((period, runtime_ip, dso_path, dso_offset))
}

fn select_samples(
    events: &str,
    expected_dso_path: &str,
    address_map: &ElfAddressMap,
    function: &Function,
) -> Result<(Vec<Sample>, SelectionTotals), String> {
    let mut samples = Vec::new();
    let mut totals = SelectionTotals::default();
    for line in events.lines().filter(|line| !line.trim().is_empty()) {
        let (period, runtime_ip, dso_path, dso_offset) = parse_perf_event(line)?;
        if dso_path != expected_dso_path {
            continue;
        }
        add(&mut totals.dso_rows, 1, "application DSO row count")?;
        add(&mut totals.dso_period, period, "application DSO period sum")?;
        let runtime_base = runtime_ip
            .checked_sub(dso_offset)
            .ok_or_else(|| format!("perf runtime IP precedes its DSO offset in {line:?}"))?;
        match totals.runtime_base {
            Some(expected) if expected != runtime_base => {
                return Err(format!(
                    "perf DSO runtime base changed from 0x{expected:x} to 0x{runtime_base:x}"
                ));
            }
            None => totals.runtime_base = Some(runtime_base),
            _ => {}
        }
        let static_address = address_map.dso_offset_to_static(dso_offset)?;
        if (function.start..function.end).contains(&static_address) {
            add(&mut totals.function_rows, 1, "function row count")?;
            add(&mut totals.function_period, period, "function period sum")?;
            samples.push(Sample {
                period,
                runtime_ip,
                dso_offset,
                static_address,
                source: line.trim().to_owned(),
            });
        } else {
            add(
                &mut totals.outside_function_rows,
                1,
                "outside-function row count",
            )?;
            add(
                &mut totals.outside_function_period,
                period,
                "outside-function period sum",
            )?;
        }
    }
    if samples.is_empty() {
        return Err(format!(
            "no perf samples normalized into {} [0x{:x}, 0x{:x}) in {expected_dso_path}",
            function.name, function.start, function.end
        ));
    }
    if totals.function_rows + totals.outside_function_rows != totals.dso_rows
        || totals.function_period + totals.outside_function_period != totals.dso_period
    {
        return Err(
            "application DSO sample selection did not conserve rows and periods".to_owned(),
        );
    }
    Ok((samples, totals))
}

fn add(total: &mut u64, value: u64, context: &str) -> Result<(), String> {
    *total = total
        .checked_add(value)
        .ok_or_else(|| format!("{context} overflow"))?;
    Ok(())
}

fn map_samples(function: &mut Function, samples: &[Sample]) -> Result<Totals, String> {
    let mut totals = Totals::default();
    for sample in samples {
        add(&mut totals.sample_rows, 1, "sample row count")?;
        add(&mut totals.period_sum, sample.period, "sample period sum")?;
        let address = sample.static_address;
        let index = function
            .instructions
            .partition_point(|instruction| instruction.address <= address);
        let mapped = index.checked_sub(1).and_then(|position| {
            let instruction = &function.instructions[position];
            (address < function.end
                && address >= instruction.address
                && address < instruction.address + instruction.size)
                .then_some(position)
        });
        if let Some(position) = mapped {
            let instruction = &mut function.instructions[position];
            add(&mut instruction.sample_count, 1, "instruction sample count")?;
            add(
                &mut instruction.period_sum,
                sample.period,
                "instruction period sum",
            )?;
            add(&mut totals.mapped_rows, 1, "mapped row count")?;
            add(
                &mut totals.mapped_period,
                sample.period,
                "mapped period sum",
            )?;
        } else {
            add(&mut totals.unmapped_rows, 1, "unmapped row count")?;
            add(
                &mut totals.unmapped_period,
                sample.period,
                "unmapped period sum",
            )?;
        }
    }
    if totals.sample_rows == 0 || totals.mapped_rows == 0 {
        return Err("perf sample file contains no mapped samples".to_owned());
    }
    if totals.mapped_rows + totals.unmapped_rows != totals.sample_rows
        || totals.mapped_period + totals.unmapped_period != totals.period_sum
    {
        return Err("instruction mapping did not conserve sample rows and periods".to_owned());
    }
    Ok(totals)
}

fn sampled_order(left: &Instruction, right: &Instruction) -> Ordering {
    right
        .period_sum
        .cmp(&left.period_sum)
        .then_with(|| right.sample_count.cmp(&left.sample_count))
        .then_with(|| left.address.cmp(&right.address))
}

fn totals_json(totals: &Totals, unmapped_percent: f64) -> Result<Json, String> {
    Ok(Json::object([
        ("sampleRows", json_u64(totals.sample_rows, "sample rows")?),
        ("periodSum", json_u64(totals.period_sum, "period sum")?),
        ("mappedRows", json_u64(totals.mapped_rows, "mapped rows")?),
        (
            "mappedPeriod",
            json_u64(totals.mapped_period, "mapped period")?,
        ),
        (
            "unmappedRows",
            json_u64(totals.unmapped_rows, "unmapped rows")?,
        ),
        (
            "unmappedPeriod",
            json_u64(totals.unmapped_period, "unmapped period")?,
        ),
        ("unmappedPeriodPercent", Json::Float(unmapped_percent)),
    ]))
}

fn selection_totals_json(totals: &SelectionTotals) -> Result<Json, String> {
    Ok(Json::object([
        (
            "applicationDsoRows",
            json_u64(totals.dso_rows, "application DSO rows")?,
        ),
        (
            "applicationDsoPeriod",
            json_u64(totals.dso_period, "application DSO period")?,
        ),
        (
            "functionRows",
            json_u64(totals.function_rows, "function rows")?,
        ),
        (
            "functionPeriod",
            json_u64(totals.function_period, "function period")?,
        ),
        (
            "outsideFunctionRows",
            json_u64(totals.outside_function_rows, "outside-function rows")?,
        ),
        (
            "outsideFunctionPeriod",
            json_u64(totals.outside_function_period, "outside-function period")?,
        ),
        (
            "runtimeBase",
            Json::string(format!(
                "0x{:x}",
                totals
                    .runtime_base
                    .ok_or_else(|| "application DSO runtime base is missing".to_owned())?
            )),
        ),
    ]))
}

fn elf_segments_json(address_map: &ElfAddressMap, capture: &Capture) -> Result<Json, String> {
    let segments = address_map
        .loads
        .iter()
        .map(|segment| {
            Ok(Json::object([
                (
                    "fileOffset",
                    Json::string(format!("0x{:x}", segment.file_offset)),
                ),
                (
                    "virtualAddress",
                    Json::string(format!("0x{:x}", segment.virtual_address)),
                ),
                (
                    "fileSize",
                    json_u64(segment.file_size, "PT_LOAD file size")?,
                ),
                (
                    "memorySize",
                    json_u64(segment.memory_size, "PT_LOAD memory size")?,
                ),
                (
                    "alignment",
                    json_u64(segment.alignment, "PT_LOAD alignment")?,
                ),
                ("flags", Json::Int(i64::from(segment.flags))),
                ("executable", Json::Bool(segment.executable())),
            ]))
        })
        .collect::<Result<Vec<_>, String>>()?;
    Ok(Json::object([
        ("schemaVersion", Json::Int(1)),
        ("binarySha256", Json::string(&capture.binary_sha256)),
        ("elfClass", Json::string("ELF64")),
        ("elfData", Json::string("little-endian")),
        ("elfMachine", Json::string("x86-64")),
        ("loadSegments", Json::Array(segments)),
    ]))
}

fn aggregate(
    output: &RunDirectory,
    function: &mut Function,
    samples: &[Sample],
    selection_totals: &SelectionTotals,
    capture: &Capture,
    expected_dso_path: &str,
    plan: &Plan,
) -> Result<(Totals, f64), String> {
    let expected_dso = dso_basename(expected_dso_path)
        .ok_or_else(|| "perf DSO path has no UTF-8 basename".to_owned())?;
    let totals = map_samples(function, samples)?;
    let unmapped_percent = totals.unmapped_period as f64 * 100.0 / totals.period_sum as f64;
    if unmapped_percent >= HARD_UNMAPPED_PERCENT {
        return Err(format!(
            "unmapped perf period {unmapped_percent:.6}% is not below the 1% hard gate"
        ));
    }
    if unmapped_percent > plan.max_unmapped_period_percent {
        return Err(format!(
            "unmapped perf period {unmapped_percent:.6}% exceeds the reviewed {:.6}% gate",
            plan.max_unmapped_period_percent
        ));
    }
    let mut ranked_instructions = function
        .instructions
        .iter()
        .filter(|instruction| instruction.sample_count > 0)
        .collect::<Vec<_>>();
    ranked_instructions.sort_by(|left, right| sampled_order(left, right));

    let instruction_rows = ranked_instructions
        .iter()
        .enumerate()
        .map(|(index, instruction)| {
            let Json::Object(mut row) = instruction_json(instruction, function.start)? else {
                unreachable!("instruction JSON is an object");
            };
            row.insert(
                "rank".to_owned(),
                json_u64(
                    u64::try_from(index + 1).map_err(|error| error.to_string())?,
                    "rank",
                )?,
            );
            row.insert(
                "samplePercent".to_owned(),
                Json::Float(instruction.sample_count as f64 * 100.0 / totals.mapped_rows as f64),
            );
            row.insert(
                "periodPercent".to_owned(),
                Json::Float(instruction.period_sum as f64 * 100.0 / totals.mapped_period as f64),
            );
            Ok(Json::Object(row))
        })
        .collect::<Result<Vec<_>, String>>()?;
    let explanation = plan
        .unmapped_period_explanation
        .as_deref()
        .map_or(Json::Null, Json::string);
    let report = Json::object([
        ("schemaVersion", Json::Int(3)),
        (
            "identity",
            Json::object([
                ("binary_sha256", Json::string(&capture.binary_sha256)),
                ("binary_build_id", Json::string(&capture.binary_build_id)),
                ("ida_function_name", Json::string(&function.name)),
                ("dso_basename", Json::string(expected_dso)),
                ("perf_dso_path", Json::string(expected_dso_path)),
                (
                    "address_normalization",
                    Json::string("perf-dso-file-offset-through-executable-elf-pt-load"),
                ),
            ]),
        ),
        (
            "mappingGate",
            Json::object([
                (
                    "maxUnmappedPeriodPercent",
                    Json::Float(plan.max_unmapped_period_percent),
                ),
                (
                    "hardMaximumPercentExclusive",
                    Json::Float(HARD_UNMAPPED_PERCENT),
                ),
                ("unmappedPeriodExplanation", explanation),
            ]),
        ),
        (
            "function",
            Json::object([
                ("name", Json::string(&function.name)),
                ("start", Json::string(format!("0x{:x}", function.start))),
                ("end", Json::string(format!("0x{:x}", function.end))),
                (
                    "size",
                    json_u64(function.end - function.start, "function size")?,
                ),
                (
                    "instructionCount",
                    json_u64(
                        u64::try_from(function.instructions.len())
                            .map_err(|error| error.to_string())?,
                        "instruction count",
                    )?,
                ),
                (
                    "sampledInstructionCount",
                    json_u64(
                        u64::try_from(ranked_instructions.len())
                            .map_err(|error| error.to_string())?,
                        "sampled instruction count",
                    )?,
                ),
            ]),
        ),
        ("selectionTotals", selection_totals_json(selection_totals)?),
        ("totals", totals_json(&totals, unmapped_percent)?),
        ("instructions", Json::Array(instruction_rows)),
    ]);
    output.write_new("instruction-hotspots.json", &report.to_python_json())?;

    let mut tsv = String::from(
        "rank\tperiod_percent\tsample_percent\tperiod_sum\tsample_count\taddress\toffset\tsize\tbytes\tinstruction\n",
    );
    for (index, instruction) in ranked_instructions.iter().enumerate() {
        let text = instruction.text.replace('\t', " ");
        let _ = writeln!(
            tsv,
            "{}\t{:.6}\t{:.6}\t{}\t{}\t0x{:x}\t0x{:x}\t{}\t{}\t{}",
            index + 1,
            instruction.period_sum as f64 * 100.0 / totals.mapped_period as f64,
            instruction.sample_count as f64 * 100.0 / totals.mapped_rows as f64,
            instruction.period_sum,
            instruction.sample_count,
            instruction.address,
            instruction.address - function.start,
            instruction.size,
            instruction.bytes,
            text
        );
    }
    output.write_new("instruction-hotspots.tsv", &tsv)?;

    let mut text = format!(
        "Function: {}\nSamples: {}/{} mapped\nUnmapped period: {:.6}%\n\nRank  Period%  Samples  Address     Offset   Instruction\n",
        function.name, totals.mapped_rows, totals.sample_rows, unmapped_percent
    );
    for (index, instruction) in ranked_instructions.iter().take(40).enumerate() {
        let _ = writeln!(
            text,
            "{:>4}  {:>7.3}  {:>7}  {:>10}  {:>7}  {}",
            index + 1,
            instruction.period_sum as f64 * 100.0 / totals.mapped_period as f64,
            instruction.sample_count,
            format!("0x{:x}", instruction.address),
            format!("0x{:x}", instruction.address - function.start),
            instruction.text
        );
    }
    output.write_new("instruction-hotspots.txt", &text)?;
    Ok((totals, unmapped_percent))
}

fn make_private_directory(path: &Path) -> Result<(), String> {
    std::fs::DirBuilder::new()
        .mode(0o700)
        .create(path)
        .map_err(|error| format!("could not create {}: {error}", path.display()))
}

fn write_tool_capture(
    output: &RunDirectory,
    stdout_name: &str,
    stderr_name: &str,
    outcome: &crate::process::Outcome,
) -> Result<(), String> {
    output.write_new(stdout_name, &outcome.stdout)?;
    output.write_new(stderr_name, &outcome.stderr)?;
    Ok(())
}

fn execute(plan: &Plan, capture: &Capture, output: &RunDirectory) -> Result<(), String> {
    let requested_dso_offset = parse_address(&plan.dso_offset, "--dso-offset")?;
    let address_map = ElfAddressMap::parse(&capture.binary)?;
    let requested = address_map.dso_offset_to_static(requested_dso_offset)?;
    if address_map.static_to_dso_offset(requested)? != requested_dso_offset {
        return Err("ELF address normalization is not reversible".to_owned());
    }
    make_private_directory(&output.join("ida"))?;
    make_private_directory(&output.join("ida-work"))?;

    let binary_name = capture
        .binary
        .file_name()
        .ok_or_else(|| "archived binary has no file name".to_owned())?;
    let ida_input = output.join("ida-work").join(binary_name);
    std::fs::copy(&capture.binary, &ida_input).map_err(|error| {
        format!(
            "could not isolate archived binary {}: {error}",
            capture.binary.display()
        )
    })?;
    let mut permissions = ida_input
        .metadata()
        .map_err(|error| format!("could not stat isolated IDA input: {error}"))?
        .permissions();
    permissions.set_mode(permissions.mode() & !0o222);
    std::fs::set_permissions(&ida_input, permissions)
        .map_err(|error| format!("could not make IDA input read-only: {error}"))?;
    if hash::sha256_file(&ida_input)? != capture.binary_sha256 {
        return Err("isolated IDA input SHA-256 mismatch".to_owned());
    }

    output.write_new(
        "elf-load-segments.json",
        &elf_segments_json(&address_map, capture)?.to_python_json(),
    )?;
    run_stdout_file(
        Path::new("readelf"),
        &["-lW".to_owned(), capture.binary.display().to_string()],
        &output.join("readelf-program-headers.txt"),
        &output.join("readelf-program-headers.stderr"),
    )?;

    let bridge = output.join("ida-work/idalib-bridge.py");
    write_new(&bridge, IDALIB_BRIDGE.as_bytes())?;
    let dwarf = Tool::new("addr2line")
        .args([
            "-e".to_owned(),
            capture.binary.display().to_string(),
            "-f".to_owned(),
            "-C".to_owned(),
            "-i".to_owned(),
            format!("0x{requested:x}"),
        ])
        .probe()
        .map_err(|error| format!("addr2line could not start: {error}"))?;
    write_tool_capture(output, "dwarf.txt", "dwarf.stderr", &dwarf)?;
    if !dwarf.success() {
        return Err(format!(
            "addr2line failed with exit code {}",
            dwarf.code.unwrap_or(128)
        ));
    }

    let raw_result = output.join("ida-work/result.json");
    let idalib = Tool::new("timeout")
        .args([
            "-k".to_owned(),
            "5s".to_owned(),
            format!("{}s", plan.timeout_seconds),
            plan.idalib_python.display().to_string(),
            bridge.display().to_string(),
            ida_input.display().to_string(),
            format!("0x{requested:x}"),
            raw_result.display().to_string(),
        ])
        .probe()
        .map_err(|error| format!("IDALib could not start: {error}"))?;
    write_tool_capture(
        output,
        "ida-work/idalib.stdout",
        "ida-work/idalib.stderr",
        &idalib,
    )?;
    if !idalib.success() {
        return Err(format!(
            "IDALib failed with exit code {}; see {}",
            idalib.code.unwrap_or(128),
            output.join("ida-work/idalib.stderr").display()
        ));
    }
    regular_not_symlink(&raw_result, "IDALib bridge result")?;
    if hash::sha256_file(&ida_input)? != capture.binary_sha256 {
        return Err("isolated IDA input changed during analysis".to_owned());
    }
    let mut function = parse_idalib_result(&raw_result, requested)?;
    address_map.static_to_dso_offset(function.start)?;
    address_map.static_to_dso_offset(function.end - 1)?;
    write_ida_outputs(output, &function, capture, &ida_input, requested)?;

    run_stdout_file(
        Path::new("llvm-objdump"),
        &[
            "--disassemble".to_owned(),
            "--demangle".to_owned(),
            "--source".to_owned(),
            "--line-numbers".to_owned(),
            "-M".to_owned(),
            "intel".to_owned(),
            format!("--start-address=0x{:x}", function.start),
            format!("--stop-address=0x{:x}", function.end),
            capture.binary.display().to_string(),
        ],
        &output.join("llvm-disassembly.txt"),
        &output.join("llvm-disassembly.stderr"),
    )?;

    let expected_dso = binary_name
        .to_str()
        .ok_or_else(|| "archived binary file name is not UTF-8".to_owned())?;
    let buildids = Tool::new("perf")
        .args([
            "buildid-list".to_owned(),
            "-i".to_owned(),
            capture.perf_data.display().to_string(),
        ])
        .run()
        .map_err(|error| format!("perf buildid-list failed: {error}"))?;
    if !super::build_id_list_contains(&buildids.stdout, &capture.binary_build_id) {
        return Err(format!(
            "perf data does not contain binary Build ID {}",
            capture.binary_build_id
        ));
    }
    let perf_dso_path =
        build_id_dso_path(&buildids.stdout, &capture.binary_build_id, expected_dso)?;
    output.write_new("perf-buildids.txt", &buildids.stdout)?;

    run_stdout_file(
        Path::new("perf"),
        &[
            "script".to_owned(),
            "-G".to_owned(),
            "--no-demangle".to_owned(),
            "-i".to_owned(),
            capture.perf_data.display().to_string(),
            "-F".to_owned(),
            "hw:ip,dsoff,period,dso".to_owned(),
        ],
        &output.join("perf-script-events.txt"),
        &output.join("perf-script-events.stderr"),
    )?;
    let events = std::fs::read_to_string(output.join("perf-script-events.txt"))
        .map_err(|error| format!("could not read perf script events: {error}"))?;
    let (samples, selection_totals) =
        select_samples(&events, &perf_dso_path, &address_map, &function)?;
    let mut sample_text = format!(
        "# binary_sha256={}\n# binary_build_id={}\n# ida_function_name={}\n# perf_dso_path={}\n# normalization=perf-dso-file-offset-through-executable-elf-pt-load\n# fields=period runtime_ip dso_offset static_address raw_perf_row\n",
        capture.binary_sha256, capture.binary_build_id, function.name, perf_dso_path
    );
    for sample in &samples {
        let _ = writeln!(
            sample_text,
            "{}\t0x{:x}\t0x{:x}\t0x{:x}\t{}",
            sample.period,
            sample.runtime_ip,
            sample.dso_offset,
            sample.static_address,
            sample.source
        );
    }
    output.write_new("perf-function-samples.txt", &sample_text)?;
    let (totals, unmapped_percent) = aggregate(
        output,
        &mut function,
        &samples,
        &selection_totals,
        capture,
        &perf_dso_path,
        plan,
    )?;

    let metadata = Json::object([
        ("schemaVersion", Json::Int(3)),
        ("state", Json::string("COMPLETE")),
        ("label", Json::string(&plan.label)),
        (
            "addressNormalization",
            Json::object([
                (
                    "method",
                    Json::string("perf-dso-file-offset-through-executable-elf-pt-load"),
                ),
                (
                    "requestedDsoOffset",
                    Json::string(format!("0x{requested_dso_offset:x}")),
                ),
                (
                    "requestedStaticAddress",
                    Json::string(format!("0x{requested:x}")),
                ),
            ]),
        ),
        (
            "capture",
            Json::object([
                ("runId", Json::string(&capture.run_id)),
                (
                    "runDirectory",
                    Json::string(capture.root.display().to_string()),
                ),
                ("binary", Json::string(capture.binary.display().to_string())),
                ("binarySha256", Json::string(&capture.binary_sha256)),
                ("binaryBuildId", Json::string(&capture.binary_build_id)),
                (
                    "perfData",
                    Json::string(capture.perf_data.display().to_string()),
                ),
                (
                    "perfDataSha256",
                    Json::string(&capture.perf_data_sha256),
                ),
                ("perfDsoPath", Json::string(&perf_dso_path)),
            ]),
        ),
        (
            "idalib",
            Json::object([
                (
                    "python",
                    Json::string(plan.idalib_python.display().to_string()),
                ),
                ("bridgeSha256", Json::string(hash::sha256_file(&bridge)?)),
                (
                    "timeoutSeconds",
                    json_u64(plan.timeout_seconds, "IDALib timeout")?,
                ),
                ("boundary", Json::string("generated-direct-api-bridge")),
            ]),
        ),
        (
            "function",
            Json::object([
                ("name", Json::string(&function.name)),
                ("start", Json::string(format!("0x{:x}", function.start))),
                ("end", Json::string(format!("0x{:x}", function.end))),
            ]),
        ),
        ("selectionTotals", selection_totals_json(&selection_totals)?),
        ("totals", totals_json(&totals, unmapped_percent)?),
    ]);
    output.write_new("metadata.json", &metadata.to_python_json())?;

    let primary_files = [
        "metadata.json",
        "dwarf.txt",
        "dwarf.stderr",
        "elf-load-segments.json",
        "readelf-program-headers.txt",
        "readelf-program-headers.stderr",
        "ida/summary.json",
        "ida/disassembly.json",
        "ida/pseudocode.c",
        "ida-work/idalib-bridge.py",
        "ida-work/result.json",
        "ida-work/idalib.stdout",
        "ida-work/idalib.stderr",
        "llvm-disassembly.txt",
        "llvm-disassembly.stderr",
        "perf-buildids.txt",
        "perf-script-events.txt",
        "perf-script-events.stderr",
        "perf-function-samples.txt",
        "instruction-hotspots.json",
        "instruction-hotspots.tsv",
        "instruction-hotspots.txt",
    ];
    let mut sums = String::new();
    let mut file_rows = Vec::with_capacity(primary_files.len());
    for relative in primary_files {
        let digest = hash::sha256_file(&output.join(relative))?;
        let _ = writeln!(sums, "{digest}  {relative}");
        file_rows.push(Json::object([
            ("path", Json::string(relative)),
            ("sha256", Json::string(digest)),
        ]));
    }
    output.write_new("SHA256SUMS", &sums)?;
    let contract = Json::object([
        ("schemaVersion", Json::Int(1)),
        ("state", Json::string("COMPLETE")),
        ("collector", Json::string("perf-hotspot-bundle")),
        ("runId", Json::string(&capture.run_id)),
        ("label", Json::string(&plan.label)),
        ("binarySha256", Json::string(&capture.binary_sha256)),
        ("binaryBuildId", Json::string(&capture.binary_build_id)),
        ("files", Json::Array(file_rows)),
        (
            "sha256sumsSha256",
            Json::string(hash::sha256_file(&output.join("SHA256SUMS"))?),
        ),
    ]);
    output.write_new("bundle-contract.json", &contract.to_python_json())?;
    publication::publish_success_marker(
        &output.join("bundle-completion.json"),
        &output.join("bundle-contract.json"),
        &format!("{}:{}", capture.run_id, plan.label),
        "perf-hotspot-bundle",
    )?;
    Ok(())
}

/// Exports and publishes one instruction-level hotspot bundle.
///
/// # Errors
///
/// Returns an argument, capture-identity, external-mechanism, mapping-gate or
/// publication diagnostic. Once created, an incomplete output is marked
/// `FAILED` and is never silently reused.
pub fn run(plan: &Plan) -> Result<String, String> {
    validate(plan)?;
    for program in ["addr2line", "llvm-objdump", "perf", "readelf", "timeout"] {
        if !Tool::exists(program) {
            return Err(format!("required tool unavailable: {program}"));
        }
    }
    let capture = load_capture(plan)?;
    let hotspots = capture.root.join("hotspots");
    match hotspots.symlink_metadata() {
        Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_dir() => {
            return Err(format!(
                "hotspots path is not a non-symlink directory: {}",
                hotspots.display()
            ));
        }
        Ok(_) => {}
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            make_private_directory(&hotspots)?;
        }
        Err(error) => {
            return Err(format!("could not inspect {}: {error}", hotspots.display()));
        }
    }
    let hotspot = hotspots.join(&plan.label);
    let output = RunDirectory::create(&hotspot)?;
    if let Err(error) = execute(plan, &capture, &output) {
        let failure = Json::object([
            ("schemaVersion", Json::Int(2)),
            ("state", Json::string("FAILED")),
            ("label", Json::string(&plan.label)),
            ("error", Json::string(&error)),
        ]);
        let _ = output.write_new("FAILED.json", &failure.to_python_json());
        return Err(error);
    }
    Ok(format!("hotspot bundle complete: {}", hotspot.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!("rr-hotspot-bundle-{}-{name}", std::process::id()))
    }

    fn fixture_function() -> Function {
        Function {
            name: "raw_symbol".to_owned(),
            start: 0x1000,
            end: 0x1004,
            instructions: vec![
                Instruction {
                    address: 0x1000,
                    size: 2,
                    bytes: "9090".to_owned(),
                    text: "nop".to_owned(),
                    sample_count: 0,
                    period_sum: 0,
                },
                Instruction {
                    address: 0x1002,
                    size: 2,
                    bytes: "c3cc".to_owned(),
                    text: "ret".to_owned(),
                    sample_count: 0,
                    period_sum: 0,
                },
            ],
            pseudocode: "return;".to_owned(),
        }
    }

    fn fixture_address_map() -> ElfAddressMap {
        ElfAddressMap {
            loads: vec![LoadSegment {
                file_offset: 0x2000,
                virtual_address: 0x1000,
                file_size: 0x100,
                memory_size: 0x100,
                alignment: 0x1000,
                flags: 5,
            }],
        }
    }

    fn fixture_sample(period: u64, static_address: u64) -> Sample {
        Sample {
            period,
            runtime_ip: 0x5000 + static_address,
            dso_offset: 0x2000 + static_address.saturating_sub(0x1000),
            static_address,
            source: String::new(),
        }
    }

    #[test]
    fn bridge_result_is_validated_before_policy_uses_it() {
        let path = scratch("idalib.json");
        let _ = std::fs::remove_file(&path);
        std::fs::write(
            &path,
            r#"{"requestedAddress":"0x1001","function":{"name":"raw_symbol","start":"0x1000","end":"0x1004"},"instructions":[{"address":"0x1000","size":2,"bytes":"9090","text":"nop"},{"address":"0x1002","size":2,"bytes":"c3cc","text":"ret"}],"pseudocode":"return;"}"#,
        )
        .unwrap();
        let function = parse_idalib_result(&path, 0x1001).expect("valid fixture");
        assert_eq!(function.instructions.len(), 2);
        assert!(parse_idalib_result(&path, 0x1002).is_err());
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn dso_offset_selection_normalizes_and_conserves_identity_exactly() {
        let events = concat!(
            "1000 5001 (/tmp/rust-reality+0x2001)\n",
            "3000 5003 (/tmp/rust-reality+0x2003)\n",
            "10 5004 (/tmp/rust-reality+0x2004)\n",
            "10 5001 (/tmp/other+0x2001)\n",
        );
        let function = fixture_function();
        let (samples, totals) = select_samples(
            events,
            "/tmp/rust-reality",
            &fixture_address_map(),
            &function,
        )
        .unwrap();
        assert_eq!(samples.len(), 2);
        assert_eq!(samples[1].static_address, 0x1003);
        assert_eq!(totals.dso_rows, 3);
        assert_eq!(
            totals.function_rows + totals.outside_function_rows,
            totals.dso_rows
        );
        assert_eq!(
            totals.function_period + totals.outside_function_period,
            totals.dso_period
        );
        assert_eq!(totals.runtime_base, Some(0x3000));
    }

    #[test]
    fn build_id_membership_binds_the_exact_perf_dso_path() {
        let build_id = "0123456789abcdef";
        let buildids = format!("{build_id} /tmp/exact/rust-reality\nfeedface /tmp/other\n");
        assert_eq!(
            build_id_dso_path(&buildids, build_id, "rust-reality").unwrap(),
            "/tmp/exact/rust-reality"
        );
        assert!(build_id_dso_path(&buildids, build_id, "other").is_err());
        assert!(
            build_id_dso_path(
                &format!("{buildids}{build_id} /tmp/duplicate\n"),
                build_id,
                "rust-reality"
            )
            .is_err()
        );
    }

    #[test]
    fn instruction_mapping_uses_static_elf_boundaries() {
        let mut function = fixture_function();
        let samples = vec![fixture_sample(1000, 0x1000), fixture_sample(3000, 0x1003)];
        let totals = map_samples(&mut function, &samples).unwrap();
        assert_eq!(totals.mapped_rows, 2);
        assert_eq!(function.instructions[1].period_sum, 3000);
    }

    #[test]
    fn unmapped_samples_remain_visible_to_the_hard_gate() {
        let mut function = fixture_function();
        let samples = vec![fixture_sample(9900, 0x1000), fixture_sample(100, 0x1005)];
        let totals = map_samples(&mut function, &samples).unwrap();
        let percent = totals.unmapped_period as f64 * 100.0 / totals.period_sum as f64;
        assert!((percent - 1.0).abs() < f64::EPSILON);
        assert!(percent >= HARD_UNMAPPED_PERCENT);
    }

    #[test]
    fn bounded_identifiers_and_thresholds_are_enforced() {
        assert!(safe_component("dispatch-loop_1.0"));
        assert!(!safe_component("../escape"));
        assert!(parse_address("0xdeadbeef", "address").is_ok());
        assert!(parse_address("deadbeef", "address").is_err());
        assert!(!valid_lower_hex("ABC", None));
    }

    #[test]
    fn elf_program_header_maps_file_offset_to_distinct_virtual_address() {
        let path = scratch("elf-address-map");
        let _ = std::fs::remove_file(&path);
        let mut elf = vec![0_u8; 0x2100];
        elf[..7].copy_from_slice(b"\x7fELF\x02\x01\x01");
        elf[16..18].copy_from_slice(&3_u16.to_le_bytes());
        elf[18..20].copy_from_slice(&62_u16.to_le_bytes());
        elf[20..24].copy_from_slice(&1_u32.to_le_bytes());
        elf[32..40].copy_from_slice(&64_u64.to_le_bytes());
        elf[52..54].copy_from_slice(&64_u16.to_le_bytes());
        elf[54..56].copy_from_slice(&56_u16.to_le_bytes());
        elf[56..58].copy_from_slice(&1_u16.to_le_bytes());
        elf[64..68].copy_from_slice(&1_u32.to_le_bytes());
        elf[68..72].copy_from_slice(&5_u32.to_le_bytes());
        elf[72..80].copy_from_slice(&0x2000_u64.to_le_bytes());
        elf[80..88].copy_from_slice(&0x3000_u64.to_le_bytes());
        elf[96..104].copy_from_slice(&0x100_u64.to_le_bytes());
        elf[104..112].copy_from_slice(&0x100_u64.to_le_bytes());
        elf[112..120].copy_from_slice(&0x1000_u64.to_le_bytes());
        std::fs::write(&path, elf).unwrap();

        let map = ElfAddressMap::parse(&path).unwrap();
        assert_eq!(map.dso_offset_to_static(0x2010).unwrap(), 0x3010);
        assert_eq!(map.static_to_dso_offset(0x3010).unwrap(), 0x2010);
        assert!(map.dso_offset_to_static(0x1fff).is_err());

        let mut malformed = std::fs::read(&path).unwrap();
        malformed[32..40].copy_from_slice(&u64::MAX.to_le_bytes());
        std::fs::write(&path, malformed).unwrap();
        assert!(ElfAddressMap::parse(&path).is_err());
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn completed_capture_binds_perf_data_and_binary_identity() {
        let root = scratch("mutated-perf-data");
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("binary")).unwrap();

        let source = std::env::current_exe().unwrap();
        let binary_name = source.file_name().unwrap();
        let binary = root.join("binary").join(binary_name);
        std::fs::copy(&source, &binary).unwrap();
        let binary_sha256 = hash::sha256_file(&binary).unwrap();
        let binary_build_id = attest::build_id(&binary).unwrap();
        let perf_data = root.join("perf.data");
        std::fs::write(&perf_data, b"original perf capture").unwrap();
        let perf_data_sha256 = hash::sha256_file(&perf_data).unwrap();
        let run_id = "hotspot-integrity-fixture";

        let metadata = Json::object([
            ("schemaVersion", Json::Int(2)),
            ("state", Json::string("COMPLETE")),
            ("runId", Json::string(run_id)),
            ("binarySha256", Json::string(&binary_sha256)),
            ("binaryBuildId", Json::string(&binary_build_id)),
        ]);
        std::fs::write(root.join("metadata.json"), metadata.to_python_json()).unwrap();
        let contract = Json::object([
            ("schemaVersion", Json::Int(2)),
            ("runId", Json::string(run_id)),
            ("collector", Json::string("perf-hotspot")),
            ("phase", Json::string("complete")),
            ("exitCode", Json::Int(0)),
            (
                "binary",
                Json::object([
                    ("sha256", Json::string(&binary_sha256)),
                    ("buildId", Json::string(&binary_build_id)),
                ]),
            ),
            (
                "perfData",
                Json::object([
                    ("relativePath", Json::string("perf.data")),
                    ("sha256", Json::string(&perf_data_sha256)),
                ]),
            ),
        ]);
        let contract_path = root.join("run-contract.json");
        std::fs::write(&contract_path, contract.to_python_json()).unwrap();
        publication::publish_success_marker(
            &root.join("run-completion.json"),
            &contract_path,
            run_id,
            "perf-hotspot",
        )
        .unwrap();
        let plan = Plan {
            run_dir: root.clone(),
            label: "integrity-fixture".to_owned(),
            dso_offset: "0x1000".to_owned(),
            idalib_python: source,
            timeout_seconds: 60,
            max_unmapped_period_percent: 0.0,
            unmapped_period_explanation: None,
        };

        load_capture(&plan).expect("the completed fixture is initially admissible");
        std::fs::write(&perf_data, b"substituted capture").unwrap();
        assert!(
            load_capture(&plan).is_err(),
            "completion must bind the exact perf.data bytes"
        );

        std::fs::write(&perf_data, b"original perf capture").unwrap();
        let substitute = Path::new("/bin/true");
        let substitute_sha256 = hash::sha256_file(substitute).unwrap();
        let substitute_build_id = attest::build_id(substitute).unwrap();
        std::fs::copy(substitute, &binary).unwrap();
        let substituted_metadata = Json::object([
            ("schemaVersion", Json::Int(2)),
            ("state", Json::string("COMPLETE")),
            ("runId", Json::string(run_id)),
            ("binarySha256", Json::string(&substitute_sha256)),
            ("binaryBuildId", Json::string(&substitute_build_id)),
        ]);
        std::fs::write(
            root.join("metadata.json"),
            substituted_metadata.to_python_json(),
        )
        .unwrap();
        assert!(
            load_capture(&plan).is_err(),
            "metadata and the archived binary must agree with the bound contract"
        );

        std::fs::remove_dir_all(root).unwrap();
    }
}
